- auth0/src/main/java/com/auth0/authentication/AuthenticationAPIClient.java
- auth0/src/main/java/com/auth0/authentication/ParameterBuilder.java
- auth0/src/test/java/com/auth0/authentication/AuthenticationAPIClientTest.java
- auth0/src/test/java/com/auth0/authentication/ParameterBuilderTest.java
Related to https://github.com/auth0/lock/issues/373 and https://github.com/auth0/auth0-users/issues/203
> Make ParameterBuilder ignore null parameters

- auth0/build.gradle
- auth0/src/main/java/com/auth0/authentication/AuthenticationAPIClient.java
- auth0/src/main/java/com/auth0/authentication/result/Credentials.java
- auth0/src/main/java/com/auth0/authentication/result/DatabaseUser.java
- auth0/src/main/java/com/auth0/authentication/result/Delegation.java
- auth0/src/main/java/com/auth0/authentication/result/JsonRequired.java
- auth0/src/main/java/com/auth0/authentication/result/JsonRequiredTypeAdapterFactory.java
- auth0/src/main/java/com/auth0/authentication/result/UserIdentity.java
- auth0/src/main/java/com/auth0/authentication/result/UserProfile.java
- auth0/src/main/java/com/auth0/request/internal/BaseAuthenticationRequest.java
- auth0/src/main/java/com/auth0/request/internal/BaseRequest.java
- auth0/src/main/java/com/auth0/request/internal/JsonRequestBodyBuilder.java
- auth0/src/main/java/com/auth0/request/internal/RequestFactory.java
- auth0/src/main/java/com/auth0/request/internal/SimpleRequest.java
- auth0/src/main/java/com/auth0/request/internal/VoidRequest.java
- auth0/src/main/java/com/auth0/util/Telemetry.java
- auth0/src/test/java/com/auth0/authentication/AuthenticationAPIClientTest.java
- auth0/src/test/java/com/auth0/authentication/result/JsonRequiredTypeAdapterFactoryTest.java
- auth0/src/test/java/com/auth0/request/internal/BaseRequestTest.java
In favor of a lesser method count library.
This PR depends on https://github.com/auth0/auth0-java/pull/25 being merged into `master` first.
> Migrate Jackson usage to Gson

- src/main/java/com/auth0/net/CustomRequest.java
Related: https://github.com/square/okhttp/issues/2311
> Close the ResponseBody after its parsed

- README.md
- src/main/java/com/auth0/client/auth/LogoutUrlBuilder.java
- src/test/java/com/auth0/client/auth/LogoutUrlBuilderTest.java
Related: https://github.com/auth0/auth0-java/issues/64
> Remove invalid Logout URL parameter

- src/main/java/com/auth0/json/mgmt/users/User.java
- src/test/java/com/auth0/json/mgmt/users/UserTest.java
Fixes https://github.com/auth0/auth0-java/issues/88
> Add user_id setter

- README.md
Fixed the returned type in the `listByEmail` snippet, and added a snippet to show how to obtain a token for the Management API v2.
> Fix listByEmail snippet and added sample for token

- .circleci/config.yml
https://github.com/codecov/codecov-bash/issues/134
> Explicitly set commit SHA and fail build if coverage is not uploaded

- src/main/java/com/auth0/json/mgmt/Connection.java
- src/test/java/com/auth0/json/mgmt/ConnectionTest.java
- src/test/resources/mgmt/connection.json
- src/test/resources/mgmt/connections_list.json
Pull request for issue #205 
- Modified Connection class to contain a new metadata field
- Added sample metadata to existing test case with Connection object
- Added sample metadata to existing MockServer test resource file
> Add metadata field to Connection object

- build.gradle
Bump dependencies to latest minors and patches.
Solve jackson-databind security issue reported in #208. 
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-174736
> Bump dependencies and solve security issues

- src/main/java/com/auth0/json/auth/TokenHolder.java
Improve the javadoc for the expires_in value.
Closes https://github.com/auth0/auth0-java/issues/211
> Update javadoc for expires_in

- src/main/java/com/auth0/client/mgmt/ManagementAPI.java
- src/main/java/com/auth0/client/mgmt/RulesConfigsEntity.java
- src/main/java/com/auth0/json/mgmt/RulesConfig.java
- src/test/java/com/auth0/client/MockServer.java
- src/test/java/com/auth0/client/mgmt/RulesConfigsEntityTest.java
- src/test/java/com/auth0/json/mgmt/RulesConfigTest.java
- src/test/resources/mgmt/rules_config.json
- src/test/resources/mgmt/rules_configs_list.json
Adds support for the Rules Config entity.
Closes https://github.com/auth0/auth0-java/issues/185
> Add Rules Configs entity

- CHANGELOG.md
- README.md
> Release 1.16.0

- src/main/java/com/auth0/json/mgmt/users/UsersPage.java
fix small typo
- Endpoints added, deleted, deprecated, or changed
- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
- Any alternative designs or approaches considered
- support ticket
- community post
- StackOverflow post
- support forum thread
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and …
> Fix typo in UsersPage.java

- src/main/java/com/auth0/utils/tokens/IdTokenVerifier.java
- src/test/java/com/auth0/utils/tokens/IdTokenVerifierTest.java
Adds API to validate an OIDC-compliant ID token. 
Accompanies and builds on #258. Validation logic is based on that in [mvc-commons](https://github.com/auth0/auth0-java-mvc-common/blob/master/src/main/java/com/auth0/IdTokenVerifier.java).
> Add ID Token verifier API

- README.md
Adds documentation to the `README` for validating an ID Token.
Documentation for changes introduced in #258 and #260
> Document ID Token Validation

- CHANGELOG.md
- README.md
> Release 1.18.0

- CHANGELOG.md
- README.md
> Release 1.21.0

- README.md
Adds a note to the readme to show how to handle the verification required error.
https://auth0.com/docs/anomaly-detection/bot-protection
> Add bot protection note to the readme

- README.md
Reverts auth0/auth0-java#286
Keeps the Log-Stream changes
> Revert "Add bot protection note to the readme"

- CHANGELOG.md
- README.md
> Release 1.22.0

- src/main/java/com/auth0/json/auth/TokenHolder.java
- src/test/java/com/auth0/json/auth/TokenHolderTest.java
Adds the scope field to the token response model.
Fixes #276
> Add scope to TokenHolder

- src/main/java/com/auth0/json/mgmt/tickets/EmailVerificationTicket.java
- src/test/java/com/auth0/client/mgmt/TicketsEntityTest.java
- src/test/java/com/auth0/json/mgmt/tickets/EmailVerificationTicketTest.java
Fixes #278 
- [Post Email Verification docs](https://auth0.com/docs/api/management/v2#!/Tickets/post_email_verification)
> Add inicludeEmailInRedirect field for create email verification ticket endpoint

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.22.1...1.23.0)
**Added**
- Add support for MFA OTP exchange [\#303](https://github.com/auth0/auth0-java/pull/303) ([jimmyjames](https://github.com/jimmyjames))
- Passwordless support [\#300](https://github.com/auth0/auth0-java/pull/300) ([jimmyjames](https://github.com/jimmyjames))
- Add scope to TokenHolder [\#297](https://github.com/auth0/auth0-java/pull/297) ([jimmyjames](https://github.com/jimmyjames))
- Add inicludeEmailInRedirect field for create email verification ticket endpoint [\#296](https://github.com/auth0/auth0-java/pull/296) ([jimmyjames](https://github.com/jimmyjames))
**Changed**
- Update dependencies [\#299](https://github.com/auth0/auth0-java/pull/299) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.23.0

- CHANGELOG.md
- README.md
Release version 1.24.0. 
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.23.0...1.24.0)
**Added**
- Add methods to determine cause of APIException [\#310](https://github.com/auth0/auth0-java/pull/310) ([jimmyjames](https://github.com/jimmyjames))
**Changed**
- Return TokenRequest instead of AuthRequest [\#309](https://github.com/auth0/auth0-java/pull/309) ([jimmyjames](https://github.com/jimmyjames))
**Fixed**
- Add unchecked warnings failures for src [\#311](https://github.com/auth0/auth0-java/pull/311) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.24.0

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.24.0...1.25.0)
**Changed**
- Update to OkHttp 4 [\#319](https://github.com/auth0/auth0-java/pull/319) ([jimmyjames](https://github.com/jimmyjames))
- Use java8 [\#316](https://github.com/auth0/auth0-java/pull/316) ([jsalinaspolo](https://github.com/jsalinaspolo))
> Release 1.25.0

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Remove references to JCenter 
Based on https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
> Remove jcenter

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.26.0...1.27.0)
**Added**
- Add support for async requests [\#328](https://github.com/auth0/auth0-java/pull/328) ([jimmyjames](https://github.com/jimmyjames))
**Changed**
- Update dependency versions [\#329](https://github.com/auth0/auth0-java/pull/329) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.27.0

- CHANGELOG.md
Version 1.24 inadvertently introduced a breaking change. This change updates the CHANGELOG to reflect that. Additionally it notes changes we have made to run API compatibility checks to ensure this doesn't happen again.
> Update Changelog for 1.24

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.27.0...1.28.0)
**Added**
- Add support for organizations feature [\#338](https://github.com/auth0/auth0-java/pull/338) ([jimmyjames](https://github.com/jimmyjames))
**Changed**
- Update Gradle OSS Plugin [\#339](https://github.com/auth0/auth0-java/pull/339) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.28.0

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.29.0...1.30.0)
**Added**
- [SDK-2537] Add missing parameters to Ticket entities [\#352](https://github.com/auth0/auth0-java/pull/352) ([jimmyjames](https://github.com/jimmyjames))
[SDK-2537]: https://auth0team.atlassian.net/browse/SDK-2537
> Release 1.30.0

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.30.0...1.31.0)
**Added**
- [SDK-2550] Add networking client timeout configuration [\#354](https://github.com/auth0/auth0-java/pull/354) ([jimmyjames](https://github.com/jimmyjames))
[SDK-2550]: https://auth0team.atlassian.net/browse/SDK-2550
> Release 1.31.0

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.32.0...1.33.0)
**Added**
- [SDK-2664] Add support for checkpoint pagination [\#362](https://github.com/auth0/auth0-java/pull/362) ([jimmyjames](https://github.com/jimmyjames))
**Deprecated**
- Deprecate unused constructors in Page implementations [\#363](https://github.com/auth0/auth0-java/pull/363) ([jimmyjames](https://github.com/jimmyjames))
[SDK-2664]: https://auth0team.atlassian.net/browse/SDK-2664
> Release 1.33.0

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.34.0...1.34.1)
**Fixed**
- Add user_name field to LogEvent [\#375](https://github.com/auth0/auth0-java/pull/375) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.34.1

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.36.0...1.36.1)
**Security**
- Update jackson dependency [\#394](https://github.com/auth0/auth0-java/pull/394) ([poovamraj](https://github.com/poovamraj))
> Release 1.36.1

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.37.0...1.38.0)
**Added**
- Support maxRequests and maxRequestsPerHost client confiugrations [\#402](https://github.com/auth0/auth0-java/pull/402) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.38.0

- src/main/java/com/auth0/client/mgmt/UsersEntity.java
`getEnrollments` only returns one enrollment
> [ESD-18148] Update UsersEntity.java

- CHANGELOG.md
- README.md
**Added**
- [SDK-3116] Add support for Attack Protection APIs [\#405](https://github.com/auth0/auth0-java/pull/405) ([jimmyjames](https://github.com/jimmyjames))
- Feature/add branding [\#399](https://github.com/auth0/auth0-java/pull/399) ([pelletier197](https://github.com/pelletier197))
**Changed**
- Feature/reduce duplication [\#381](https://github.com/auth0/auth0-java/pull/381) ([pelletier197](https://github.com/pelletier197))
[SDK-3116]: https://auth0team.atlassian.net/browse/SDK-3116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 1.39.0

- build.gradle
Updates to latest dependency version of `java-jwt`.
> Update java-jwt dependency

- CHANGELOG.md
- README.md
See `CHANGELOG` additions for release contents.
> Release 1.40.0

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.41.0...1.42.0)
**Added**
- Added support for Key management API [\#431](https://github.com/auth0/auth0-java/pull/431) ([poovamraj](https://github.com/poovamraj))
- Support for custom scheme URL [\#429](https://github.com/auth0/auth0-java/pull/429) ([poovamraj](https://github.com/poovamraj))
- Add enabled connections on organization [\#426](https://github.com/auth0/auth0-java/pull/426) ([charliearaya](https://github.com/charliearaya))
> Release 1.42.0

- src/main/java/com/auth0/json/mgmt/client/Client.java
- src/test/resources/mgmt/clients_list.json
We have added some missing parameters to the Client response object.
https://github.com/auth0/auth0-java/issues/443
> Add missing fields in Client model

- settings.gradle
Updates to the latest OSS gradle publishing plugin, which resolves some M1 chip build issues.
> Update to OSS plugin version 0.17.2

- CHANGELOG.md
- README.md
**Added**
- Add support for deleting all user's authenticators [\#451](https://github.com/auth0/auth0-java/pull/451) ([jimmyjames](https://github.com/jimmyjames))
- Add session idle lifetime and make session lifetime doubles [\#423](https://github.com/auth0/auth0-java/pull/423) ([pelletier197](https://github.com/pelletier197))
- #448 Adding field filter option to get client by ID API [\#449](https://github.com/auth0/auth0-java/pull/449) ([bhatmadhavi](https://github.com/bhatmadhavi))
- Add missing fields in Client model [\#444](https://github.com/auth0/auth0-java/pull/444) ([poovamraj](https://github.com/poovamraj))
- Add Ship CLI configuration [\#433](https://github.com/auth0/auth0-java/pull/433) ([frederikprijck](https://github.com/frederikprijck))
**Changed**
- Update to OSS plugin …
> Release 1.43.0

- .circleci/config.yml
- .shiprc
- build.gradle
Adds the `ship-orb` to enable automated releases.
> Integrate ship orb

- CHANGELOG.md
- README.md
- build.gradle
**Added**
- Integrate ship orb [\#458](https://github.com/auth0/auth0-java/pull/458) ([jimmyjames](https://github.com/jimmyjames))
- [SDK-2558] Add support for tenant session cookie [\#457](https://github.com/auth0/auth0-java/pull/457) ([jimmyjames](https://github.com/jimmyjames))
- Support stage property on Breached Password Detection [\#456](https://github.com/auth0/auth0-java/pull/456) ([ewanharris](https://github.com/ewanharris))
**Changed**
- Update to Gradle 6.9.2 [\#455](https://github.com/auth0/auth0-java/pull/455) ([jimmyjames](https://github.com/jimmyjames))
[SDK-2558]: https://auth0team.atlassian.net/browse/SDK-2558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 1.44.0

- src/main/java/com/auth0/client/mgmt/filter/DeviceCredentialsFilter.java
- src/main/java/com/auth0/client/mgmt/filter/UserFilter.java
- src/main/java/com/auth0/client/mgmt/filter/UsersExportFilter.java
- src/main/java/com/auth0/client/mgmt/filter/UsersImportOptions.java
- src/test/java/com/auth0/client/mgmt/filter/DeviceCredentialsFilterTest.java
- src/test/java/com/auth0/client/mgmt/filter/UserFilterTest.java
- src/test/java/com/auth0/client/mgmt/filter/UsersExportFilterTest.java
- src/test/java/com/auth0/client/mgmt/filter/UsersImportOptionsTest.java
We have gone through the list of filters in the management API and updated the missing ones.
Added unit tests
> [SDK-3751] Update missing filters for Management APIs

- MIGRATION_GUIDE.md
This PR adds a new migration guide with information about migrating from v1 -> v2.
> [SDK-3875] Added migration guide

- src/main/java/com/auth0/json/mgmt/logstreams/LogStream.java
- src/main/java/com/auth0/json/mgmt/logstreams/LogStreamFilter.java
- src/test/java/com/auth0/client/mgmt/LogStreamsEntityTest.java
- src/test/resources/mgmt/log_stream.json
- src/test/resources/mgmt/log_streams_list.json
Add support for [Log Stream filters](https://auth0.com/docs/api/management/v2#!/Log_Streams/get_log_streams_by_id) as raised and mostly implemented in #493 🙇
Closes #493
> Support LogStream filters

- src/main/java/com/auth0/net/RateLimitInterceptor.java
- src/test/java/com/auth0/net/RateLimitInterceptorTest.java
Currently, if an exception occurs during a retry attempt, a `FailsafeException` will be thrown instead of an `Auth0Exception`. This is demonstrated in #483. 
To test, I created a pre-user-registration action that simply times out, then call the `signUp` API. Prior to this change, a `FailsafeException` is thrown as shown in the issue. With this change, an `Auth0Exception` is thrown with the underlying cause.
> Throw Auth0Exception when failure occurs during retries

- .circleci/config.yml
- build.gradle
Disables auto-publishing for v2.
> Disable auto-publishing

- build.gradle
Updates to the latest `java-jwt` version.
> Update to latest java-jwt version

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/2.0.0-beta.0...2.0.0-beta.1)
**Added**
- Add support for MFA APIs [\#505](https://github.com/auth0/auth0-java/pull/505) ([poovamraj](https://github.com/poovamraj))
- Add support MFA Methods API [\#506](https://github.com/auth0/auth0-java/pull/506) ([poovamraj](https://github.com/poovamraj))
- Support JWT Client Authentication [\#507](https://github.com/auth0/auth0-java/pull/507) ([jimmyjames](https://github.com/jimmyjames))
> Release 2.0.0-beta.1

- build.gradle
> Update to latest java-jwt

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java/compare/2.0.0-beta.1...2.0.0-beta.2)
**Changed**
- Update to latest java-jwt version [\#512](https://github.com/auth0/auth0-java/pull/512) ([jimmyjames](https://github.com/jimmyjames))
> Release 2.0.0-beta.2

- README.md
Remove beta notice from README that came in from merge.
> remove beta notice from README

- build.gradle
Updates `java-jwt` dependency to latest (4.4.0)
> Update java-jwt dependency to 4.4.0

- .circleci/config.yml
Change to fix the codecov upload in CI
https://github.com/auth0/ruby-auth0/pull/465
> Fix Codecov uploader in CI

- src/main/java/com/auth0/net/BaseRequest.java
- src/test/java/com/auth0/client/MockServer.java
change headers to lowerscase during RateLimitException
issue https://github.com/auth0/auth0-java/issues/527
Tested on real system, getting big amout of data from auth0,
- [ V] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [V ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [ V] All existing and new tests complete without errors
> Fix headers to the lowercase 

- CHANGELOG.md
- README.md
**Added**
- Add support for Pushed Authorization Requests [\#451](https://github.com/auth0/auth0-java/pull/531) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.45.0

- CHANGELOG.md
- README.md
**Added**
- Add support for client credential management [\#525](https://github.com/auth0/auth0-java/pull/525) ([jimmyjames](https://github.com/jimmyjames)) 
**Fixed**
- Fix headers to lowercase [\#528](https://github.com/auth0/auth0-java/pull/528) ([alexz75](https://github.com/alexz75))
> Release 2.2.0

- CHANGELOG.md
- README.md
**Added**
- Support Pushed Authorization Requests [\#534](https://github.com/auth0/auth0-java/pull/534) ([jimmyjames](https://github.com/jimmyjames))
> Release 2.3.0

- CHANGELOG.md
- README.md
**Added**
- Support Organization Name on Authorize URL [\#550](https://github.com/auth0/auth0-java/pull/550) ([vasantteja](https://github.com/vasantteja))
**Fixed**
- Fix deleteAuthenticationMethodById [\#552](https://github.com/auth0/auth0-java/pull/552) ([jimmyjames](https://github.com/jimmyjames))
> Release 2.5.0

- .github/workflows/snyk.yml
Use the `pull_request_target` event instead of `pull_request` for snyk check.
> use pull_reqeust_target event

- CHANGELOG.md
- README.md
**Fixed**
- Propagate error messages on rate limit exceptions [\#579](https://github.com/auth0/auth0-java/pull/579) ([jimmyjames](https://github.com/jimmyjames))
> Release 2.8.0

- CHANGELOG.md
- README.md
**Added**
- Support organization in client credentials [\#582](https://github.com/auth0/auth0-java/pull/582) ([jimmyjames](https://github.com/jimmyjames))
> Release 2.9.0

- .snyk
ignore snyk warning for test dependency
> ignore bouncycastle test dependency from snyk

- .semgrepignore
This PR adds a `.semgrepignore` disallow file to ensure Semgrep tooling does not incorrectly flag test code with warnings.
N/A
N/A
> ci: Add `.semgrepignore`

- .github/actions/maven-publish/action.yml
- .github/workflows/java-release.yml
Currently the version is not properly retrieved from the project. Do avoid this we are getting the version from .version file
> Add version to publish logic

- .github/actions/maven-publish/action.yml
The current release command doesn't pick the right version so we have updated it to reflect the old command we use
> Update release command 

- .github/actions/maven-publish/action.yml
Adding signing gradle command explicitly as it is not called during build
> Add signing task to gradle command

- .github/workflows/java-release.yml
We had commented out to test the workflow. Now that we have verified the workflows we can uncomment it and continue with the release
> Uncomment tag creation process

- src/main/java/com/auth0/client/auth/AuthAPI.java
- src/test/java/com/auth0/client/auth/AuthAPITest.java
Adds support for JWT-secured authorization requests (JAR) and authorization code flow with Pushed Authorization Requests (PAR) and JAR.
- [Authorization Code Flow with JAR](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow/authorization-code-flow-with-jar)
- [Authorization Code Flow with PAR and JAR](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow/authorization-code-flow-with-par-and-jar)
> [SDK-4763] - add support for JAR and PAR with JAR to Authentication API

- .github/actions/maven-publish/action.yml
- .github/workflows/java-release.yml
- .github/workflows/release.yml
- Updated github workflow, changes performed in release.yml, java-release.yml and action.yml file.
Auth0 Android SDK
> Updated workflow secrets to use ossr-token

- .github/workflows/release.yml
Removed the is-android input from the with section of the release.yml
> Updated release.yml workflow

- gradle/maven-publish.gradle
> Updated gradle config

- .github/workflows/release.yml
- Endpoints added, deleted, deprecated, or changed
- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
- Any alternative designs or approaches considered
- support ticket
- community post
- StackOverflow post
- support forum thread
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should …
> Reversing Labs Scanner artifact name fix

- src/main/java/com/auth0/json/mgmt/organizations/EnabledConnection.java
- src/test/java/com/auth0/json/mgmt/organizations/EnabledConnectionsPageTest.java
- src/test/java/com/auth0/json/mgmt/organizations/EnabledConnectionsTest.java
- added field is_signup_enabled to EnabledConnection
> Added is_signup_enabled field to OrganizationConnection 

- build.gradle
> Migrated bouncycastle to jdk18on

- build.gradle
> Added groovy version compatible with java 8

- build.gradle
Removing groovy from dependency
> Removed groovy from dependency

- EXAMPLES.md
Ref - https://github.com/auth0/auth0-java/pull/658
> Update EXAMPLES.md to fix variable usage

- CHANGELOG.md
**Added**
- Update EXAMPLES.md to fix variable usage [\#690](https://github.com/auth0/auth0-java/pull/690) ([tanya732](https://github.com/tanya732))
- Added Support for Self-Service-Profile [\#683](https://github.com/auth0/auth0-java/pull/683) ([tanya732](https://github.com/tanya732))
- Added support for Back Channel Login [\#682](https://github.com/auth0/auth0-java/pull/682) ([tanya732](https://github.com/tanya732))
> Release 2.17.0

- .github/actions/maven-publish/action.yml
- build.gradle
- Remove debug log from Pipeline
- Add java 17, 21 in test
> Removed debug log option

- .github/actions/maven-publish/action.yml
- .github/workflows/java-release.yml
Added JAVA_HOME Path
https://github.com/auth0/java-jwt/pull/715
> Added JAVA_HOME

- .github/workflows/build-and-test.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/rl-scanner.yml
Bumped codecov-action, setup-gradle and gradle wrapper-validation versions
Note - This PR fixes #650, #656, #657
> Update github workflow

- gradle/maven-publish.gradle
Removed manually referencing the .jar file
> Updated maven publish ci
