auth0/auth0-java

core/src/main/java/com/auth0/Auth0Exception.java
core/src/main/java/com/auth0/authentication/AuthenticationAPIClient.java
core/src/main/java/com/auth0/authentication/AuthenticationRequest.java
core/src/main/java/com/auth0/authentication/ChangePasswordRequest.java
core/src/main/java/com/auth0/authentication/DelegationRequest.java
core/src/main/java/com/auth0/authentication/SignUpRequest.java
core/src/main/java/com/auth0/authentication/api/APIException.java
core/src/main/java/com/auth0/authentication/api/Request.java
core/src/main/java/com/auth0/authentication/api/callback/Callback.java
core/src/main/java/com/auth0/authentication/api/internal/ApplicationInfoRequest.java
core/src/main/java/com/auth0/authentication/api/internal/BaseRequest.java
core/src/main/java/com/auth0/authentication/api/internal/SimpleRequest.java
core/src/main/java/com/auth0/authentication/api/internal/VoidRequest.java
core/src/test/java/com/auth0/authentication/AuthenticationAPIClientTest.java
core/src/test/java/com/auth0/authentication/api/internal/BaseRequestTest.java
core/src/test/java/com/auth0/authentication/api/util/MockBaseCallback.java

Add a method execute() to all the requests. 
It's the equivalent to start() but this method blocks the current thread until the response is received, then returns the parsed response object.
In case of error this methods throws a Auth0Exception (the same that would have been used in the callback's onFailure)
Include tests for all async tests

Add sync (blocking) mode to all requests

---

auth0/src/main/java/com/auth0/request/internal/BaseRequest.java

Without this the GET method of RequestFactory is useless.
I need this for management api: https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id

Do not add request body if there's nothing to add

---

src/main/java/com/auth0/client/auth/AuthorizeUrlBuilder.java
src/test/java/com/auth0/client/auth/AuthorizeUrlBuilderTest.java

The custom parameters are `String` both key and value.

Add response_type and custom parameter setter for AuthorizeUrlBuilder

---

src/main/java/com/auth0/json/mgmt/users/Identity.java
src/test/java/com/auth0/json/mgmt/users/IdentityTest.java

Parse extra values contained in the received Identity into a Map.
I've found that `access_token_secret`, `expires_in` and `refresh_token` might be included in the Identities object. We might think about having those specific getters instead of the proposed generic Map.
Fixes https://github.com/auth0/auth0-java/issues/41

Parse extra Auth0 Identity values

---

README.md
src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/auth/AuthorizeUrlBuilder.java
src/main/java/com/auth0/client/auth/LogoutUrlBuilder.java
src/main/java/com/auth0/client/mgmt/BaseManagementEntity.java
src/main/java/com/auth0/client/mgmt/BlacklistsEntity.java
src/main/java/com/auth0/client/mgmt/ClientGrantsEntity.java
src/main/java/com/auth0/client/mgmt/ClientsEntity.java
src/main/java/com/auth0/client/mgmt/ConnectionsEntity.java
src/main/java/com/auth0/client/mgmt/DeviceCredentialsEntity.java
src/main/java/com/auth0/client/mgmt/EmailProviderEntity.java
src/main/java/com/auth0/client/mgmt/GuardianEntity.java
src/main/java/com/auth0/client/mgmt/LogEventsEntity.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/client/mgmt/RulesEntity.java
src/main/java/com/auth0/client/mgmt/StatsEntity.java
src/main/java/com/auth0/client/mgmt/TenantsEntity.java
src/main/java/com/auth0/client/mgmt/TicketsEntity.java
src/main/java/com/auth0/client/mgmt/UserBlocksEntity.java
src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/auth/AuthorizeUrlBuilderTest.java
src/test/java/com/auth0/client/auth/LogoutUrlBuilderTest.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java

Renew the authentication using a `refresh_token`.
Closes https://github.com/auth0/auth0-java/issues/48

Add renew authentication endpoint

---

build.gradle
src/main/java/com/auth0/client/mgmt/LogEventsEntity.java
src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/main/java/com/auth0/client/mgmt/filter/LogEventFilter.java
src/main/java/com/auth0/client/mgmt/filter/QueryFilter.java
src/main/java/com/auth0/client/mgmt/filter/UserFilter.java
src/test/java/com/auth0/client/mgmt/LogEventsEntityTest.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
src/test/java/com/auth0/client/mgmt/filter/LogEventFilterTest.java
src/test/java/com/auth0/client/mgmt/filter/QueryFilterTest.java
src/test/java/com/auth0/client/mgmt/filter/UserFilterTest.java

It seems that OkHttp it's not really URL encoding the query parameters, or that some chars are missing from that implementation, which affects both the `UsersEntity#list` and `LogsEntity#list` methods. This PR encodes the query value (and only that case) using `java.net.URLEncoder`. The client/entity later, only for that parameter, adds it to the request as a pre-encoded query parameter, in order to avoid OkHttp to encode again the `%` escaped chars.
Personally I don't like being checking in the `for` loop for a specific parameter name and adding it in a different way. Maybe it's better that the whole networking impl uses the `URLEncoder` first for all parameters and then adds them as "already encoded" to the request. Opinions?
Fixes https://github.com/auth0/auth0-java/issues/54

Fix "q" query parameter encoding

---

src/main/java/com/auth0/json/mgmt/users/ProfileData.java
src/main/java/com/auth0/json/mgmt/users/User.java
src/test/java/com/auth0/json/mgmt/users/ProfileDataTest.java
src/test/java/com/auth0/json/mgmt/users/UserTest.java
src/test/resources/mgmt/user.json
src/test/resources/mgmt/users_list.json
src/test/resources/mgmt/users_paged_list.json

When logging in with a social provider like Facebook, most of the profile properties go to the `user` root. Also when linking accounts, some of these properties end up inside `indentity.profileData`. This PR solves both by adding generic getters for all those values that are not already obtainable with a getter.
Related conversation in https://github.com/auth0/auth0-java/pull/45

Add getter for User and ProfileData extra properties

---

src/main/java/com/auth0/json/mgmt/users/User.java

User **must have a connection** when they are first created, but then if you want to change a property you must set a connection again (which **cannot** be changed). Related: https://github.com/auth0/auth0-java/issues/58#issuecomment-307226536

Add public User constructor without parameters

---

src/main/java/com/auth0/json/mgmt/Connection.java
src/test/java/com/auth0/json/mgmt/ConnectionTest.java

Create a string property for the pojo to support provisioning_ticket_url json property of the management api v2.
To be linked to this issue: https://github.com/auth0/auth0-java/issues/66

Add support for provisioning_ticket_url property to Connection POJO

---

.gitignore
src/main/java/com/auth0/client/mgmt/GrantsEntity.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/json/mgmt/Grant.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/GrantsEntityTest.java
src/test/java/com/auth0/json/mgmt/GrantTest.java
src/test/resources/mgmt/grants_list.json

The Grants endpoint of the management API was missing. Since I need it in one of my projects, I decided to directly add it to the official library. Also added unit tests.
Somehow, the git diff here at github marks some changes as a complete remove and add. However, in .gitignore, I only added a NetBeans IDE ignore pattern at the end and in ManagementAPI.java, only lines 118-125 were added.

implemented /api/v2/grants endpoint of auth0 management api

---

src/main/java/com/auth0/client/mgmt/filter/LogEventFilter.java
src/main/java/com/auth0/client/mgmt/filter/QueryFilter.java
src/main/java/com/auth0/client/mgmt/filter/UserFilter.java
src/test/java/com/auth0/client/mgmt/filter/QueryFilterTest.java

With this small fix, the API is easier to use, since the consumer does not have to handle the UnsupportedEncodingException which is neither motivated nor documented in javadoc.

removed unmotivated throwing of UnsupportedEncodingException

---

build.gradle

Upgrades jackson-databind to latest version

Closes #78

---

README.md
src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/json/auth/CreatedUser.java
src/main/java/com/auth0/json/auth/UserInfo.java
src/main/java/com/auth0/net/CreateUserRequest.java
src/main/java/com/auth0/net/SignUpRequest.java
src/main/java/com/auth0/net/VoidRequest.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/net/CreateUserRequestTest.java
src/test/java/com/auth0/net/VoidRequestTest.java
src/test/resources/auth/sign_up.json
src/test/resources/auth/sign_up_username.json

To the reviewer:
- Name of the `SignUpRequest` interface's implementation class. I used `CreateUserRequest`. User's will receive an instance with the interface name instead (as that's what the method signature defines), but because all the request classes are public scoped I'd like to leave this well. To be honest I could just name it "SignUpRequestImpl".
- Type of signup response. I'm using the one from the /userinfo endpoint, which it's just a generic `Map<String, Object>` holder with a getter for "all values". The alternative is to create a new class with the 4 parameters returned by the signup endpoint.
- Evaluate the impact of this PR as a breaking change. Because the method was returning a wrong object I would consider this as a fix and break it anyway. But the fix included even …

Include a proper SignUp response

---

src/main/java/com/auth0/net/VoidRequest.java

Wish I could test this in an easy way but that would require extending OkHttp classes to store the "closed" state. 
Will fix https://github.com/auth0/auth0-java/issues/100

Close ResponseBody buffer after read

---

README.md
src/main/java/com/auth0/client/mgmt/EmailTemplatesEntity.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/json/mgmt/EmailTemplate.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/EmailTemplatesEntityTest.java
src/test/java/com/auth0/json/mgmt/EmailTemplateTest.java
src/test/resources/mgmt/email_template.json

Add the email-templates endpoints 
https://auth0.com/docs/api/management/v2#!/Email_Templates/get_email_templates_by_templateName
Things open to discuss:
- The use of constants. They can be provided by us or not. The problem is that the endpoint only accepts a given set of values. We can also use an Enum class instead. I've added this:
```java
public static final String TEMPLATE_VERIFY_EMAIL = "verify_email";
public static final String TEMPLATE_RESET_EMAIL = "reset_email";
public static final String TEMPLATE_WELCOME_EMAIL = "welcome_email";
public static final String TEMPLATE_BLOCKED_ACCOUNT = "blocked_account";
public static final String TEMPLATE_STOLEN_CREDENTIALS = "stolen_credentials";
public static final String TEMPLATE_ENROLLMENT_EMAIL = "enrollment_email";
public static final …
```

Add email-templates endpoints

---

src/main/java/com/auth0/client/mgmt/ClientsEntity.java
src/main/java/com/auth0/client/mgmt/filter/ClientFilter.java
src/main/java/com/auth0/json/mgmt/PageDeserializer.java
src/main/java/com/auth0/json/mgmt/client/ClientsPage.java
src/main/java/com/auth0/json/mgmt/client/ClientsPageDeserializer.java
src/main/java/com/auth0/json/mgmt/logevents/LogEventsPage.java
src/main/java/com/auth0/json/mgmt/logevents/LogEventsPageDeserializer.java
src/main/java/com/auth0/json/mgmt/users/UsersPage.java
src/main/java/com/auth0/json/mgmt/users/UsersPageDeserializer.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/ClientsEntityTest.java
src/test/resources/mgmt/clients_paged_list.json

This PR refactors the way "Page Deserializers" work to prepare them for a generic approach. It also adds a ClientFilter and a new `list(filter)` under the clients entity to send pagination parameters, among others. 
A separate PR will deprecate the existing `list()` method, once this one is merged so it can reference the new one.

Support pagination on the Clients entity

---

build.gradle

Bump libraries and plugins dependencies to latest versions. This also fixes a security issue found on jackson databind.

Security fix and dependencies update

---

src/main/java/com/auth0/client/mgmt/filter/QueryFilter.java
src/main/java/com/auth0/client/mgmt/filter/UserFilter.java
src/test/java/com/auth0/client/mgmt/filter/UserFilterTest.java

Since the search_engine v2 is no longer allowed for new tenants and it's going to be shut down on November 13th this year, this PR adds a setter to specify a different value than the default one.
Fixes https://github.com/auth0/auth0-java/issues/133

Allow to set search_engine version

---

README.md
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/client/mgmt/ResourceServerEntity.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java

As I wrote this I thought that good alternative would be to have a function with a callback the user can implement their own logic in. So they can code a token refresher and feed that instead. 
Fixes: https://github.com/auth0/auth0-java/issues/131

Allow to update the Management API token

---

src/main/java/com/auth0/json/mgmt/client/Client.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java

This attribute was missing from the SDK. Added to the Auth0 MGMT API on the CORS auth update.

Add web_origins attribute to the Client class

---

src/main/java/com/auth0/exception/RateLimitException.java
src/main/java/com/auth0/net/CustomRequest.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/net/CustomRequestTest.java

This PR resolve #99 to allow get the rate limit values from `X-RateLimit-*` headers.
I have made some decisions for default values, for example, when an http response code with value `429` is received then the information about rate limits should be recovered from headers `X-RateLimit-*`, but I don't know if these values are always sent so, if I couldn't get some header then a default `-1` will be assigned.
The primitive data type chosen was `long` since the `X-RateLimit-Reset` is a Unix timestamp and the others values are normal numbers.

support to retrieve rate limits values from response headers #99

---

src/main/java/com/auth0/json/mgmt/client/Client.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java

This includes missing grant_types in the client and allows for updating
this field with the ClientEntity.
This fixes #162

Include grant_types in Client

---

src/main/java/com/auth0/json/auth/UserInfo.java
src/main/java/com/auth0/json/mgmt/users/Identity.java
src/main/java/com/auth0/json/mgmt/users/ProfileData.java
src/main/java/com/auth0/json/mgmt/users/User.java

I was tasked with implementing a custom shiro sessionDAO so we can share user session between our DropWizard web application servers. I was getting `java.io.NotSerializableException: com.auth0.json.mgmt.users.User` errors so I tried a few different workarounds like using Jackson's ObjectMapper to serialize the data, but that had its own complications (mainly SimplePrincipalCollection.realmPrincipals didn't get serialized.) 
With this change I'm now able to serialize my org.apache.shiro.session.mgt.SimpleSession and send it to other webservers to create a HA environment. 
Here is the stacktrace I was getting (with `-Dsun.io.serialization.extendedDebugInfo=true` enabled)
```
WARN  [2018-11-30 18:36:31,949]: Unable to update session …
```

Add Serializable to the user data.

---

src/main/java/com/auth0/json/mgmt/tickets/PasswordChangeTicket.java
src/test/java/com/auth0/json/mgmt/tickets/PasswordChangeTicketTest.java

Hi Auth0 Team,
according to the Management API v2 documentation, _/password-change_ endpoint accepts a new extra parameter, namely **mark_email_as_verified**.  The current version of auth0-java client API is missing this feature. 
We would like to utilize this feature in our service and use the official client library. 
Thank you in advance.
Best regards,
Yevhenii.
A new field has been added to the class definition and a corresponding unit test has been updated.
[Management API v2: Create a password change ticket](https://auth0.com/docs/api/management/v2#!/Tickets/post_password_change)
Although the change is really small and is covered by a test, I performed a small local test and creating a password change ticket using the patched auth0-java library:
```kotlin
import …
```

Add "mark_email_as_verified" property to PasswordChangeTicket

---

README.md

The GET /user API endpoint doesn't accept the `q` query parameter. That's only reserved for user listing scenarios. But because the method that calls it accepts a `UserFilter` instance, this PR will clarify that it will only be used to obtain the list of fields to include/exclude from the response.
Closes https://github.com/auth0/auth0-java/issues/188
Doc change. No needed.

Update GET /user documentation on README.md file

---

src/main/java/com/auth0/client/mgmt/filter/UserFilter.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
src/test/java/com/auth0/client/mgmt/filter/UserFilterTest.java

This SDK was hardcoding the `search_engine` to `v2` by default. This version was deprecated on June and is **no longer available since November 13th 2018**. This PR removes the default value in order to make use of the server's default (latest). Currently, this version is `v3`.
If this change is not introduced and users do not set explicitly a version e.g. v3, then requests would fail with an "invalid search_engine version" message.
We encourage the users to migrate to the latest version by following the guide [here](https://auth0.com/docs/users/search/v3/migrate-search-v2-v3).
- V3: https://auth0.com/docs/users/search/v3
- V2: https://auth0.com/docs/users/search/v2
- Migration: https://auth0.com/docs/users/search/v3/migrate-search-v2-v3

Remove default version for search_engine

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/net/Telemetry.java
src/main/java/com/auth0/net/TelemetryInterceptor.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java
src/test/java/com/auth0/net/TelemetryInterceptorTest.java
src/test/java/com/auth0/net/TelemetryTest.java

- Use the new telemetry format
- Make Telemetry class public
- Allow `AuthAPI` and `ManagementAPI` clients to set a new custom telemetry instance. 
`SDK-700`

Update Telemetry format and allow to customize it

---

src/test/java/com/auth0/json/mgmt/tickets/PasswordChangeTicketTest.java

Improved unit test coverage, and added a unit test for covering the case of creating a PasswordChangeTicket using an email and custom connection as parameters.
Improved from 70% to 100
%.

Add test case for PasswordChangeTicket with Email

---

src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java

This is to resolve the problem described in issue #198. 
- Update to the `removeRoles` and `addRoles` methods of the `UsersEntity` class to accept a list of strings instead of a list of roles. 
- Update to the `UsersEntityTest` to correctly invoke the updated methods. 
Issue #198

Fix for issue #198: Core Authorization fails when adding Roles to User

---

build.gradle
src/main/java/com/auth0/BuildConfig.java
src/main/java/com/auth0/net/TelemetryInterceptor.java

Fixes a bug where the `version` value sent on the telemetry was not obtained dynamically. This fix required a change on our OSS plugin first, that's the reason for the plugin bump.
Deployed to the local maven repository and tested on a sample app. After a simple request to the API, the log included the new version.

Dynamically obtain the project version for telemetry

---

src/main/java/com/auth0/client/mgmt/GrantsEntity.java
src/main/java/com/auth0/client/mgmt/ResourceServerEntity.java
src/main/java/com/auth0/client/mgmt/RolesEntity.java
src/main/java/com/auth0/json/mgmt/EmailTemplate.java
src/main/java/com/auth0/json/mgmt/ResourceServer.java
src/main/java/com/auth0/json/mgmt/client/Client.java
src/main/java/com/auth0/json/mgmt/users/User.java
src/test/java/com/auth0/client/mgmt/ResourceServerEntityTest.java
src/test/java/com/auth0/json/mgmt/ResourceServerTest.java
src/test/resources/mgmt/resource_server.json
src/test/resources/mgmt/resource_servers_list.json
src/test/resources/mgmt/resource_servers_paged_list.json

Adds `token_dialect` and `enforce_policies` properties to the `ResourceServer` object

Add missing ResourceServer properties

---

src/main/java/com/auth0/json/mgmt/DeviceCredentials.java
src/test/java/com/auth0/json/mgmt/DeviceCredentialsTest.java
src/test/resources/mgmt/device_credentials.json
src/test/resources/mgmt/device_credentials_list.json

This `client_id` getter was missing from `DeviceCredentials`

Add getter for DeviceCredentials client_id

---

build.gradle

**Changes**
Bump `jackson-databind` dependency to address CVE-2019-12384 and CVE-2019-12814
**References**
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-450917
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-450207

Update jackson-databind dependency to fix security vulnerability

---

src/main/java/com/auth0/net/Telemetry.java

JDK 9 was now uploading the right telemetry version, and so a `null` was being registered.
No additional tests as these are static methods and depend on the JVM they are being run on.

Find the right JDK version for Telemetry

---

src/main/java/com/auth0/json/auth/TokenHolder.java

- JavaDoc fix for `TokenHolder.getExpiresIn()`. Should be `@return` not `@returns`. 
- This fixes failure on javaDoc Gradle task (also included when running the `build` task)
- N/A
- Successful `build` and `check` tasks ran.

Fix JavaDoc

---

build.gradle

Update `jackson-databind` dependency to 2.10.0.pr3 to address CVE.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14540

Update jackson-databind to address CVE

---

src/main/java/com/auth0/json/mgmt/client/Client.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java

The property should be modifiable, as per the updated docs.
Closes #229

Allow to set the client is_first_party property

---

.gitignore
src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/json/mgmt/tickets/PasswordChangeTicket.java
src/main/java/com/auth0/json/mgmt/users/User.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/json/mgmt/tickets/PasswordChangeTicketTest.java
src/test/java/com/auth0/json/mgmt/users/UserTest.java

Fixes #234 
**Included changes:**
* Use a character array (`char[]`) instead of `String` for password fields
**Changes to follow, not in this PR:**
* Deprecation of String-based password APIs. Will be done in separate PR for changelog and tracking purposes
* GH issue: #234
* [Baeldung article about using char array instead of strings for passwords](https://www.baeldung.com/java-storing-passwords)
* [StackOverflow discussion](https://stackoverflow.com/questions/8881291/why-is-char-preferred-over-string-for-passwords)

Use char array for passwords

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/json/mgmt/client/Client.java
src/main/java/com/auth0/json/mgmt/tickets/PasswordChangeTicket.java
src/main/java/com/auth0/json/mgmt/users/User.java

* Deprecates APIs that use passwords as Strings.
* Related to #242 

deprecated string password APIs

---

src/main/java/com/auth0/json/auth/CreatedUser.java
src/test/java/com/auth0/json/auth/CreatedUserTest.java

When a new user is created via the signup endpoint, the user id value could be returned in different properties, depending on the connection where this user was created on. The properties include `_id` (default), `id` (custom DB connections), and `user_id` (custom external DB connections).
Luckily, this was easy to solve using Jackson annotations for providing alternative aliases. 
Fixes https://github.com/auth0/auth0-java/issues/176.
Tests were added to ensure there was no introduced breaking change in behavior.

Make CreatedUser take the id from different properties

---

src/main/java/com/auth0/client/mgmt/JobsEntity.java
src/main/java/com/auth0/client/mgmt/filter/UsersExportFilter.java
src/main/java/com/auth0/json/mgmt/jobs/Job.java
src/main/java/com/auth0/json/mgmt/jobs/UsersExportField.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/JobsEntityTest.java
src/test/java/com/auth0/client/mgmt/filter/UsersExportFilterTest.java
src/test/java/com/auth0/json/mgmt/jobs/JobTest.java
src/test/java/com/auth0/json/mgmt/jobs/UsersExportFieldTest.java
src/test/resources/mgmt/job_post_users_exports.json

Adds the following endpoint:
- POST Users Export Job (by connection id)
Will close https://github.com/auth0/auth0-java/issues/95

Add Job "POST User Exports" endpoint

---

src/main/java/com/auth0/net/CustomRequest.java
src/main/java/com/auth0/net/CustomizableRequest.java
src/main/java/com/auth0/net/EmptyBodyRequest.java
src/main/java/com/auth0/net/ExtendedBaseRequest.java
src/main/java/com/auth0/net/FormDataRequest.java
src/main/java/com/auth0/net/MultipartRequest.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/net/CustomRequestTest.java
src/test/java/com/auth0/net/EmptyBodyRequestTest.java
src/test/java/com/auth0/net/MultipartRequestTest.java
src/test/java/com/auth0/net/multipart/FilePart.java
src/test/java/com/auth0/net/multipart/KeyValuePart.java
src/test/java/com/auth0/net/multipart/RecordedMultipartRequest.java
src/test/resources/mgmt/multipart-sample.json

Implements a new class to handle multipart requests. This is required before implementing the "import users" Job endpoint.
These multipart requests are only allowed for HTTP methods other than GET. Some of the shared logic between `CustomRequest` and the introduced `MultipartRequest` has been moved _up_ to a class named `ExtendedBaseRequest` (as it's adding things on top of `BaseRequest`). This shared logic class is package-private!
**To review:**
Check the commit history!! First, I added the new request class. Then I added tests for that. Then I added a few helper classes for the tests. Lastly, I refactored and extracted the common parts to the shared logic class.
Please, do check for public API breaking changes. There shouldn't be any, but is always good to have another pair of eyes …

Add a new class to handle Multipart requests

---

src/main/java/com/auth0/json/mgmt/DeviceCredentials.java

Just doc comments for DeviceCredentials.Type missing the new `rotating_refresh_token` type.

Add rotating_refresh_token to devicecredential token types.

---

src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/main/java/com/auth0/json/mgmt/Permission.java
src/main/java/com/auth0/json/mgmt/PermissionSource.java
src/test/java/com/auth0/client/mgmt/RolesEntityTest.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
src/test/java/com/auth0/json/mgmt/permissions/PermissionSourceTest.java
src/test/java/com/auth0/json/mgmt/permissions/PermissionTest.java
src/test/java/com/auth0/json/mgmt/permissions/PermissionsPageTest.java

Adds a missing property to the Permission object. Mostly boilerplate code.
Closes https://github.com/auth0/auth0-java/issues/246
I've added missing tests for the `Permission` and its page object as well.

Add missing "sources" property to the Permission

---

build.gradle

#258 introduced tests that use the bouncycastle `PemReader`. The dependency on bouncycastle was not explicitly declared, instead it was being exported from the [okhttp3 mockwebserver](https://github.com/square/okhttp/tree/master/mockwebserver). As seen in #231, later versions of okhttp are no longer exporting this dependency for clients, causing build errors.

Explicit dependency on bouncycastle for tests

---

build.gradle
src/test/java/com/auth0/client/RecordedRequestMatcher.java
src/test/java/com/auth0/client/mgmt/LogEventsEntityTest.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java

* Updates to OkHttp 3.14.9, continuing the work started in #231.
* Updates `RecordedRequestMatcher.matchesQueryParameter` to use the `HttpUrl` and query methods instead of parsing the path manually. Also enables tests to expect the unencoded query parameter values.
See the discussion on #231 for context and background regarding OkHttp changes to query parameter encoding (tl;dr - Since v3.10.0 more characters are being encoded).

Update to OkHttp 3.14.9

---

src/main/java/com/auth0/json/mgmt/Connection.java
src/test/java/com/auth0/json/mgmt/ConnectionTest.java

Adds the missing `display_name` property to the Connection class.
* Closes https://github.com/auth0/auth0-java/issues/252.
* Resolves `SDK-1624`

Add display_name property to Connection

---

src/main/java/com/auth0/client/ClientOptions.java
src/main/java/com/auth0/client/HttpOptions.java
src/main/java/com/auth0/client/ProxyOptions.java
src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java

This PR adds a new constructor for both `AuthAPI` and `ManagementAPI` classes that accepts a set of `ClientOptions` (final name can still change). 
The idea is that from now on, every new property that we want to configure in the OkHttpClient comes through this options object. This way, we reduce the exposure of third-party classes in our public API.
For now, this Options object accepts a `ProxyOptions` object (final name also subject to change), that will hold the **Proxy** instance and any basic authentication, if required.
```java
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 9090));
ProxyOptions proxyOptions = new ProxyOptions(proxy);
//proxyOptions.setBasicAuthentication("johndoe", "psswd".toCharArray()); //- Optional
HttpOptions httpOptions = new …
```

Add support for java Proxy with basic auth

---

src/main/java/com/auth0/client/mgmt/LogStreamsEntity.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/json/mgmt/logstreams/LogStream.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/LogStreamsEntityTest.java
src/test/java/com/auth0/json/mgmt/logstreams/LogStreamsTest.java
src/test/resources/mgmt/log_stream.json
src/test/resources/mgmt/log_streams_list.json

This PR adds support for the Log Streams APIs available in the Management API. A new entity, `LogStreamsEntity` is added along with the following public APIs:
- Create a Log Stream: ` public Request<LogStream> create(LogStream logStream)`
- List all Log Streams: `public Request<List<LogStream>> list()`
- Get a specific Log Stream: `public Request<LogStream> get(String logStreamId)`
- Update a Log Stream: `public Request<LogStream> update(String logStreamId, LogStream logStream)`
- Delete a Log Stream: `public Request delete(String logStreamId)`
A new domain model, `LogStream` is also included in this PR.
- [Log Streaming feature documentation](https://auth0.com/docs/logs/export-log-events-with-log-streaming)
- [Log Streaming API documentation](https://auth0.com/docs/api/management/v2#!/Log …

Add support for Log Streams

---

.github/workflows/gradle-wrapper-validation.yml

This is so it shows a more descriptive text in the checks before it's run. Also, is how you see it on the branch protection settings.

Rename gradlew validation github action

---

src/main/java/com/auth0/client/mgmt/JobsEntity.java
src/main/java/com/auth0/json/mgmt/EmailVerificationIdentity.java
src/main/java/com/auth0/json/mgmt/tickets/EmailVerificationTicket.java
src/test/java/com/auth0/client/mgmt/JobsEntityTest.java
src/test/java/com/auth0/json/mgmt/tickets/EmailVerificationTicketTest.java

Adds support for specifying the (optional) `identity` object when creating email verification tickets or jobs. This is needed when verifying emails when the primary is social, enterprise, or passwordless. Also needed to verify secondary identities.
- https://auth0.com/docs/api/management/v2#!/Tickets/post_email_verification
- https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email
In addition to unit tests, I've also verified the changes manually using a real tenant and users.

Add support for identity field for email verification jobs and tickets

---

src/main/java/com/auth0/json/mgmt/DailyStats.java
src/main/java/com/auth0/json/mgmt/guardian/Enrollment.java
src/main/java/com/auth0/json/mgmt/jobs/Job.java
src/main/java/com/auth0/json/mgmt/logevents/LogEvent.java
src/main/java/com/auth0/json/mgmt/users/User.java
src/test/java/com/auth0/json/JsonTest.java
src/test/java/com/auth0/json/mgmt/users/UserTest.java
src/test/resources/mgmt/user.json

Remove our custom date serialization/deserialization patterns, as it is not strictly ISO-8601 compliant. We've seen failures on deserialization when the milliseconds field (which are optional in ISO-8601) are not sent, for example.
Instead, we can use the standard Jackson date serialization and deserialization, which uses ISO-8601 format.
- [StdDateFormat](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/util/StdDateFormat.java) (default date format used for serialization and deserialization)
- [W3C Date/Time Formats](w3.org/TR/NOTE-datetime)

Use Standard Jackson Date serialization

---

CHANGELOG.md
README.md

Release version 1.22.1
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.22.0...1.22.1)
**Fixed**
- Use Standard Jackson Date serialization [\#295](https://github.com/auth0/auth0-java/pull/295) ([jimmyjames](https://github.com/jimmyjames))

Release 1.22.1

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/test/java/com/auth0/client/auth/AuthAPITest.java

Fixes #280 and supersedes work started in #281.
Adds a new public API to exchange an MFA one-time password (OTP) for a set of tokens:
`public AuthRequest exchangeMfaOtp(String mfaToken, char[] otp)`
- #280 
- #281 
- [API Docs](https://auth0.com/docs/api/authentication#verify-with-one-time-password-otp-)

Add support for MFA OTP exchange

---

src/main/java/com/auth0/exception/APIException.java
src/test/java/com/auth0/exception/APIExceptionTest.java

Resolves #279.
Adds methods to `APIException` to help determine the cause of the underlying `APIException`, similar to how `Auth0.Android` [handles this](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.java#L180-L205). Other methods can be added in the future as needed.
- #279
There is no existing test for `APIException`; this change adds a test class but only adds tests for the added functionality.

Add methods to determine cause of APIException

---

build.gradle
src/main/java/com/auth0/exception/APIException.java
src/test/java/com/auth0/exception/APIExceptionTest.java

_This is primarily a tech debt and future preparedness PR_
`APIException` currently performs an unsafe (in compiler terms) cast of the error description to a `Map<String, Object>`. Functionally, this shouldn't be an issue since a `ClassCastException` would only come from a change in the error schema, which shouldn't happen.
However, it does cause an unchecked cast warning, which we should typically not have or suppress as needed. This change does the following:
- Updates `APIException` to only create a `PasswordStrengthErrorParser` if the error description is a map (currently it would fail with a runtime exception if not a string)
- Suppresses the unchecked exception when casting the error description to `Map<String, Object>`
- Adds tests to cover this change and the …

Add unchecked warnings failures for src

---

build.gradle
src/main/java/com/auth0/net/CustomRequest.java
src/main/java/com/auth0/net/EmptyBodyRequest.java
src/main/java/com/auth0/net/MultipartRequest.java

Updates the OkHttp dependency to version 4.
Details on the changes contained in version 4 can be found [here](https://square.github.io/okhttp/upgrading_to_okhttp_4/) (impacts are intentionally small). 
I did change three usages of `RequestBody.create` to reverse the parameter order to resolve deprecation warnings, as [documented by OkHttp](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/RequestBody.kt#L180).  
- https://square.github.io/okhttp/upgrading_to_okhttp_4/

Update to OkHttp 4

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
settings.gradle

Upgrade to Gradle 6.7.1 to fix gradle toolchain in ubuntu
Fix publish artifacts using latest gralde auth0 plugin 
Requires publishing version 0.13.0 
https://github.com/auth0/oss-library-gradle-plugin/pull/23
https://github.com/gradle/gradle/issues/15049
https://docs.gradle.org/6.7.1/release-notes.html
Locally publish artifacts

Fix publishing

---

src/main/java/com/auth0/json/mgmt/client/Client.java
src/main/java/com/auth0/json/mgmt/client/RefreshToken.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java
src/test/java/com/auth0/json/mgmt/client/RefreshTokenTest.java

Proposed solution to issue #318 
This PR includes a new object for managing the configuration of refresh tokens associated with a client, as well as the addition of the class (`RefreshToken`) as an instance variable on the `Client` class. The design is a 1-to-1 mapping of the refresh token configuration as defined in the [Auth0 Management API](https://auth0.com/docs/api/management/v2#!/Clients/get_clients).
I did not include enums for the `rotation_type` or `expiration_type` fields in the refresh token configuration like what was done in https://github.com/auth0/auth0.net/pull/451/ as the rest of the Java API relies on strings for all areas that would otherwise use enums.
This change is meant to allow for the use of documented API functionality which is currently unavailable in the SDK.
* …

Add refresh token configuration object to client

---

build.gradle

When we updated to OkHttp4, the logging interceptor version was missed. This change fixes that to use v4, as well as pulls out dependency versions into extension properties, for those that we have multiple dependencies on.
- #324 
I've verified that the logging works again with this update, but it does not resolve the issue reported in #324. Further discussion on possible causes of that can be found in the issue conversation.

Fix OkHttp dependency version

---

CHANGELOG.md
README.md

Releasing version 1.26.0. 
[Full Changelog](https://github.com/auth0/auth0-java/compare/1.25.0...1.26.0)
**Added**
- Add refresh token configuration object to client [\#321](https://github.com/auth0/auth0-java/pull/321) ([JakeUskoski](https://github.com/JakeUskoski))
**Fixed**
- Fix OkHttp dependency version [\#325](https://github.com/auth0/auth0-java/pull/325) ([jimmyjames](https://github.com/jimmyjames))
- Tidy up code [\#317](https://github.com/auth0/auth0-java/pull/317) ([jsalinaspolo](https://github.com/jsalinaspolo))

Release 1.26.0

---

build.gradle
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/net/CustomRequestTest.java
src/test/java/com/auth0/net/MultipartRequestTest.java

Updates dependency versions.
The test changes are to replace the [now-deprecated](http://hamcrest.org/JavaHamcrest/javadoc/2.0.0.0/deprecated-list.html) method `isEmptyOrNullString` with `emptyOrNullString`

Update dependency versions

---

README.md
src/main/java/com/auth0/net/BaseRequest.java
src/main/java/com/auth0/net/Request.java
src/test/java/com/auth0/net/BaseRequestTest.java
src/test/java/com/auth0/net/RequestTest.java

Fixes #315 
This change adds the ability to execute a request asynchronously, through the addition of a new default method on the `Request` interface:
```java
default CompletableFuture<T> executeAsync()
```
The default interface implementation throws an `UnsupportedOperationException`. The implementation in `BaseRequest` returns a [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html). An example usage:
```java
api.users().list(null).executeAsync().whenComplete((usersPage, ex) -> {
if (ex != null) {
System.out.println("Exception occurred: " + ex.getMessage());
} else {
System.out.println("Users list size: " + usersPage.getItems().size());
}
}).get();
```

Add support for async requests

---

src/main/java/com/auth0/net/Request.java

In #328, we added the JavaDoc tags `@apiNote` and `@implSpec`. These are not available in Java8 (they are in Java9). Removing the tags to fix JavaDoc generation.

Fix JavaDoc tags for Java8

---

README.md

Spring's dependency management defines okhttp v3 as part of its exported BOM, which collides with okhttp v4 used by this library. This results in `java.lang.NoSuchMethodError` when making requests, as reported in #324. Unfortunately we cannot control how Spring exports its dependencies, so this PR updates the README to include the workaround of specifying okhttp v4 in the spring dependency management configuration.
- [Spring Boot maven plugin docs](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/)
- [Spring Boot gradle dependency plugin docs](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/)
- #324 
Solution tested by creating both a maven and gradle project using the spring boot plugins. Without the bom override, …

Update README for Spring Boot dependency collisions

---

README.md
src/main/java/com/auth0/client/auth/AuthorizeUrlBuilder.java
src/main/java/com/auth0/utils/tokens/IdTokenVerifier.java
src/test/java/com/auth0/client/auth/AuthorizeUrlBuilderTest.java
src/test/java/com/auth0/utils/tokens/IdTokenVerifierTest.java

This PR adds support for the (beta) Organizations and User Invitations features. Changes included:
- Supports specifying the `organization` and `invitation` query parameters when building the Authorization URL
- Supports verification of the `org_id` claim in `IdTokenVerifier`
- Adds documentation for using the Organizations and User Invitations features
In addition to unit tests, the change was tested using an application and tenant with the Organizations feature enabled. I verified that with this change it adds the organization and invitation query parameters to the authorization URL to enable login/joining an organization.

Add support for organizations feature

---

settings.gradle

Updates to version `0.15.1` of the OSS plugin, which supports publishing directly to Sonatype instead of Bintray.

Update Gradle OSS Plugin

---

README.md
src/main/java/com/auth0/net/CustomRequest.java
src/main/java/com/auth0/net/EmptyBodyRequest.java
src/main/java/com/auth0/net/MultipartRequest.java

After updating to OkHttp v4, customers may experience `NoSuchMethodError` when making requests with this library, if OkHttp v3 is taking precedence on the runtime classpath. Given that OkHttp v4 is binary compatible with OkHttp v3, this change reverts to using (now-deprecated) OkHttp methods that do not exist in v4.
We cannot guarantee that we will never use any OkHttp v4 APIs, and the resolution to such issues may require managing the dependencies as discussed in #324. But for now, we can alleviate this issue for the majority of customers with this change.
- https://square.github.io/okhttp/upgrading_to_okhttp_4/
- #324

Fix `NoSuchMethodError` when projects have OkHttp 3 dependency

---

CHANGELOG.md
README.md

[Full Changelog](https://github.com/auth0/auth0-java/compare/1.28.0...1.28.1)
**Fixed**
- Fix `NoSuchMethodError` when projects have OkHttp 3 dependency [\#342](https://github.com/auth0/auth0-java/pull/342) ([jimmyjames](https://github.com/jimmyjames))

Release 1.28.1

---

README.md

* Removes blockquote from org_id claim validation documentation, to ensure the information is highlighted rather than appearing as an afterthought
* Links to the [Auth0 Tokens and Orgs docs](https://auth0.com/docs/organizations/using-tokens)

[SDK-2458] Updated guidance for working with tokens and organizations

---

src/main/java/com/auth0/client/mgmt/OrganizationsEntity.java
src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java

* Adds a method to [get an organization's connection by ID](https://auth0.com/docs/api/management/v2#!/Organizations/get_enabled_connections_by_connectionId)
* Adds links to the API documentation for new Organizations endpoints to the JavaDocs
* Related to #341

Adds method to get an organization's enabled connection and update JavaDocs

---

README.md

Now that the Organizations feature is GA, removing the feature overview documentation from the README; that information can be found in the linked Auth0 docs.

Remove summary of Orgs feature from README

---

build.gradle
src/main/java/com/auth0/net/Telemetry.java
src/test/java/com/auth0/net/TelemetryTest.java

Removes the `commons-codec` dependency, which was used for Base64 encoding/decoding, and replaces it with Java's built-in Base64 support.

[SDK-2519] Remove commons-codec dependency

---

src/main/java/com/auth0/json/mgmt/tickets/EmailVerificationTicket.java
src/main/java/com/auth0/json/mgmt/tickets/PasswordChangeTicket.java
src/test/java/com/auth0/json/mgmt/tickets/EmailVerificationTicketTest.java
src/test/java/com/auth0/json/mgmt/tickets/PasswordChangeTicketTest.java

Adds missing body parameters to [create an email verification ticket](https://auth0.com/docs/api/management/v2#!/Tickets/post_email_verification) and to [create a password change ticket](https://auth0.com/docs/api/management/v2#!/Tickets/post_password_change).
The following fields were added to the `EmailVerificationTicket` entity:
* `client_id`
* `organization_id`
The following fields were added to the `PasswordChangeTicket` entity:
* `client_id`
* `includeEmailInRedirect`
This resolves #351

[SDK-2537] Add missing parameters to Ticket entities

---

README.md
src/main/java/com/auth0/client/HttpOptions.java
src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java

Adds the ability to configure connect and read timeouts for both the `ManagementAPI` and `AuthAPI` clients through the existing `HttpOptions`:
```java
HttpOptions options = new HttpOptions();
options.setConnectTimeout(15); // default is 10 seconds
options.setReadTimeout(5); // default is 10 seconds
AuthAPI authAPI = new AuthAPI("{CLIENT_ID}", "{CLIENT_SECRET}", options);
ManagementAPI mgmtAPI = new ManagementAPI("{DOMAIN}", "{TOKEN}", options);
```

[SDK-2550] Add networking client timeout configuration

---

build.gradle
settings.gradle

This PR updates the OSS release plugin version to 0.16.0, which makes use of a newer Javadoc HTML template.
I also removed the bintray plugin which is no longer used.

Update OSS release plugin version

---

src/main/java/com/auth0/json/auth/TokenHolder.java
src/main/java/com/auth0/json/auth/TokenHolderDeserializer.java
src/test/java/com/auth0/json/auth/TokenHolderTest.java

The response from `/oauth/token` includes an `expires_in` field, which is the time (from issuance) that the access token expires in. As noted in #356, customers wishing to know the expiry status of the token need to manage this manually, by calculating the expiry time from the issuance and `expires_in` value. This change introduces a new calculated value to `TokenHolder` that represents the expiration time of the access token.
* See the individual commit history to see how tests and refactorings were introduced to mitigate any unintended side effects (added tests for regression cases, refactored to custom deserializer, then added new calculated field)
* `Date` type was used for the new `expiresAt` field, to provide consistency with other types (customers can use `Date.from(Instant value)` …

[SDK-2622] Add expiresAt to token response

---

src/main/java/com/auth0/client/mgmt/filter/PageFilter.java
src/main/java/com/auth0/json/mgmt/Page.java
src/main/java/com/auth0/json/mgmt/PageDeserializer.java
src/main/java/com/auth0/json/mgmt/organizations/MembersPage.java
src/main/java/com/auth0/json/mgmt/organizations/MembersPageDeserializer.java
src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPage.java
src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPageDeserializer.java
src/main/java/com/auth0/json/mgmt/users/UsersPage.java
src/main/java/com/auth0/json/mgmt/users/UsersPageDeserializer.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
src/test/java/com/auth0/client/mgmt/RolesEntityTest.java
src/test/java/com/auth0/client/mgmt/filter/PageFilterTest.java
src/test/java/com/auth0/json/mgmt/organizations/MembersPageTest.java
src/test/java/com/auth0/json/mgmt/organizations/OrganizationsPageTest.java
src/test/java/com/auth0/json/mgmt/users/UsersPageTest.java
src/test/resources/mgmt/organization_members_checkpoint_paged_list.json
src/test/resources/mgmt/organizations_checkpoint_paged_list.json
src/test/resources/mgmt/role_users_checkpoint_paged_list.json

This change adds checkpoint pagination support to the following APIs:
* `OrganizationEntity#list(PageFilter filter)`
* `OrganizationEntity#getMembers(String orgId, PageFilter filter)`
* `RolesEntity#listUsers(String roleId, PageFilter filter)`
While the methods listed above are not changed directly, the following changes enable supporting checkpoint pagination:
* Added new methods `withFrom(String from)` and `withTake(int take)` to `PageFilter` to support the `from` and `take` query parameters.
* Added a new field to the `Page` POJO for the `next` field that may be returned when using checkpoint pagination, along with a new constructor that accepts the `next` parameter.
* Added a new method to `PageDeserializer` to create a `Page` with the `next` parameter. Unlike the other methods in …

[SDK-2664] Add support for checkpoint pagination

---

src/main/java/com/auth0/json/mgmt/organizations/MembersPage.java
src/main/java/com/auth0/json/mgmt/organizations/MembersPageDeserializer.java
src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPage.java
src/main/java/com/auth0/json/mgmt/organizations/OrganizationsPageDeserializer.java
src/main/java/com/auth0/json/mgmt/users/UsersPage.java
src/main/java/com/auth0/json/mgmt/users/UsersPageDeserializer.java

As part of #362, new constructors were added to response types that may included checkpoint paginated responses. Per the discussion on that PR, it was recommended that these constructors be deprecated to signal the (internal) usage should prefer construction that can accept the `next` field for paginated responses.

Deprecate unused constructors in Page implementations

---

build.gradle
src/main/java/com/auth0/client/HttpOptions.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/net/RateLimitInterceptor.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java
src/test/java/com/auth0/net/RateLimitInterceptorTest.java

This change adds the ability to retry requests to the Management API that fail due to a rate-limit (429) error. It does so through a new [OkHttp Interceptor](https://square.github.io/okhttp/interceptors/) and the [failsafe library](https://failsafe-lib.github.io/https://failsafe-lib.github.io/).
Details:
* By default, 429 responses are retried three times
* The maximum retries are configurable, between zero and ten. A value of zero results in no retries.
* Retries are configured with an initial delay of 100ms, using an exponential backoff, up to a maximum of 1 second. A jitter factor of 0.2 is applied.
* The configuration of maximum retries is done via the `HttpOptions` object. If/when retries are applied to authentication requests, a similar configuration point will be added for clients …

[SDK-2686] Add retry on rate limit errors for management API

---

README.md

- Updated UserFilter `pageNumber` to `0` instead of `1` since first page is 0 as per https://auth0.com/docs/api/management/v2#!/Users/get_users
- I copied the example and was not getting any users back even though there are users in the Auth0 management portal. Quickly realized as the request included page 1 and size 20 and there were only 8 users in the management dashboard, the response returned no users. After changing the pageNumber to `0`, users were returned correctly.

Updated page number to start at 0

---

src/main/java/com/auth0/json/mgmt/logevents/LogEvent.java
src/test/java/com/auth0/json/mgmt/logevents/LogEventTest.java

This change adds the `user_name` field to the `LogEvent` entity, which was previously missing.

Add user_name field to LogEvent

---

src/main/java/com/auth0/client/mgmt/BaseManagementEntity.java
src/main/java/com/auth0/client/mgmt/GuardianEntity.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/GuardianEntityTest.java
src/test/resources/mgmt/guardian_authentication_policies_list.json

I added the endpoints for that were missing. This is kind of required to enable the MFA for your application. 
- Getting MFA policies. https://auth0.com/docs/api/management/v2#!/Guardian/get_policies  
- Update MFA policies https://auth0.com/docs/api/management/v2#!/Guardian/put_policies 
```java
AuthAPI auth = new AuthAPI("<>", "<>", "<>");
ManagementAPI api = new ManagementAPI("<>", auth.requestToken("<>").execute().getAccessToken());
System.out.println(api.guardian().getAuthenticationPolicies().execute());
System.out.println(api.guardian().updateAuthenticationPolicies(Arrays.asList("all-applications")).execute());
System.out.println(api.guardian().getAuthenticationPolicies().execute());
System.out.println(api.guardian().updateAuthenticationPolicies(Arrays.asList()).execute()); …
```

Add MFA Authentication policies to GuardianEntity

---

src/main/java/com/auth0/json/mgmt/organizations/Invitation.java
src/test/java/com/auth0/json/mgmt/organizations/InvitationTest.java

The Invitation object has an array of strings for the `roles` ids. This is NOT an object and thus, should not be serialized wrapped as an object.
Fixes #378 without introducing breaking changes.
Manually tested with the following snippets. Also, fixed unit tests.
```java
static void assignRole(ManagementAPI api) {
try {
api.organizations().addRoles(ORG_ID,
USER_ID,
new Roles(Arrays.asList(ADMIN_ROLE_ID)))
.execute();
} catch (Auth0Exception e) {
e.printStackTrace();
}
}
static void listInvitations(ManagementAPI api) {
try {
// Originally failed when invitation contains one or more Roles
InvitationsPage page = api.organizations().getInvitations(ORG_ID, null).execute();
for (Invitation i : page.getItems()) {
System.out.println(i);
}
} catch (Auth0Exception e) {
e.printStackTrace();
}
} …
```

Fix de/serialization of Invitation roles

---

src/main/java/com/auth0/client/mgmt/ClientGrantsEntity.java
src/main/java/com/auth0/client/mgmt/DeviceCredentialsEntity.java
src/main/java/com/auth0/client/mgmt/EmailProviderEntity.java
src/main/java/com/auth0/client/mgmt/GuardianEntity.java
src/main/java/com/auth0/client/mgmt/LogStreamsEntity.java
src/main/java/com/auth0/client/mgmt/OrganizationsEntity.java
src/main/java/com/auth0/client/mgmt/RolesEntity.java
src/main/java/com/auth0/client/mgmt/RulesConfigsEntity.java
src/main/java/com/auth0/client/mgmt/UserBlocksEntity.java
src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/test/java/com/auth0/client/mgmt/ActionsEntityTest.java
src/test/java/com/auth0/client/mgmt/BlacklistsEntityTest.java
src/test/java/com/auth0/client/mgmt/ClientGrantsEntityTest.java
src/test/java/com/auth0/client/mgmt/ClientsEntityTest.java
src/test/java/com/auth0/client/mgmt/ConnectionsEntityTest.java
src/test/java/com/auth0/client/mgmt/DeviceCredentialsEntityTest.java
src/test/java/com/auth0/client/mgmt/EmailProviderEntityTest.java
src/test/java/com/auth0/client/mgmt/GrantsEntityTest.java
src/test/java/com/auth0/client/mgmt/LogStreamsEntityTest.java
src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
src/test/java/com/auth0/client/mgmt/RolesEntityTest.java
src/test/java/com/auth0/client/mgmt/RulesConfigsEntityTest.java
src/test/java/com/auth0/client/mgmt/RulesEntityTest.java
src/test/java/com/auth0/client/mgmt/UserBlocksEntityTest.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java

I Added specific typing for void requests. This is important because first, IDEs usually give warnings when an object's type is not specified. It does not do anything at runtime because of type-erasure, but it makes it impossible for the IDE to know what is supposed to come out of that object. 
This causes a small inconvenience when using the library. In my case, I wrapped the auth0 library with custom code that handles Rate-limiting better and automatically execute requests, which is why the dynamic typing is needed.
I was therefore forced to specify myself the `Any` type (because the library doesn't specify the `Void`)
Does not impact tests. It just removes warnings.

remove warning for untyped requests

---

src/main/java/com/auth0/utils/tokens/IdTokenVerifier.java

Fixes #387 by exposing the `withOrganization` builder method on the `IdTokenVerifier`.

[SDK-2975] Fix withOrganization method visibility on token verifier

---

CHANGELOG.md
README.md

Release 1.36.0.
**Fixed**
- [SDK-2975] Fix withOrganization method visibility on token verifier [\#388](https://github.com/auth0/auth0-java/pull/388) ([jimmyjames](https://github.com/jimmyjames))
- remove warning for untyped requests [\#385](https://github.com/auth0/auth0-java/pull/385) ([pelletier197](https://github.com/pelletier197))
[SDK-2975]: https://auth0team.atlassian.net/browse/SDK-2975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 1.36.0

---

build.gradle

We are upgrading Jackson dependency to 12.6 due to vulnerability in the current version
[Link](https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698)
Since this is a dependency upgrade, we checked it using our existing unit tests

Update jackson dependency

---

src/main/java/com/auth0/client/HttpOptions.java
src/main/java/com/auth0/client/LoggingOptions.java
src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java

Currently, logging of HTTP request/response information is only enabled through the `setLoggingEnabled(boolean enabled)` method on the `ManagementAPI` and `AuthAPI` API clients. While this does allow for enabling or disabling logging (disabled by default), as discussed in #389 the configurability of the logging can be improved.
This PR adds a new configuration point to our existing `HttpOptions` config object. It does so by exposing a new method, `HttpOptions#setLoggingOptions(LoggingOptions loggingOptions)`. 
The `LoggingOptions` class exposes the ability to customize the logging level to any of OkHttp's supported levels, as well as the ability to specify headers that should be redacted from the logs (it does not expose any of the OkHttp functionality publicly). 
A follow-up PR will be …

Improve logging

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java

Follow-up to the changes introduced in #392, this change deprecates the `setLoggingEnabled(Boolean enabled)` in favor of configuring the HTTP logging via the `HttpOptions` when building the client.

Deprecate setLoggingEnabled on API clients

---

src/main/java/com/auth0/json/mgmt/Connection.java
src/test/java/com/auth0/json/mgmt/ConnectionTest.java

Updates the `Connection` entity to add support for the `realms` attribute.
https://auth0.com/docs/api/management/v2#!/Connections/post_connections

Add support for Connection realms

---

CHANGELOG.md
README.md

**Added**
- Add support for Connection realms [\#397](https://github.com/auth0/auth0-java/pull/397) ([jimmyjames](https://github.com/jimmyjames))
- Improve logging [\#392](https://github.com/auth0/auth0-java/pull/392) ([jimmyjames](https://github.com/jimmyjames))
**Deprecated**
- Deprecate setLoggingEnabled on API clients [\#396](https://github.com/auth0/auth0-java/pull/396) ([jimmyjames](https://github.com/jimmyjames))

Release 1.37.0

---

src/main/java/com/auth0/client/mgmt/AttackProtectionEntity.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/json/mgmt/attackprotection/BreachedPassword.java
src/main/java/com/auth0/json/mgmt/attackprotection/BruteForceConfiguration.java
src/main/java/com/auth0/json/mgmt/attackprotection/Stage.java
src/main/java/com/auth0/json/mgmt/attackprotection/StageEntry.java
src/main/java/com/auth0/json/mgmt/attackprotection/SuspiciousIPThrottlingConfiguration.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/AttackProtectionEntityTest.java
src/test/java/com/auth0/json/mgmt/attackprotection/BreachedPasswordTest.java
src/test/java/com/auth0/json/mgmt/attackprotection/BruteForceConfigurationTest.java
src/test/java/com/auth0/json/mgmt/attackprotection/SuspiciousIPThrottlingConfigurationTest.java
src/test/resources/mgmt/breached_password_settings.json
src/test/resources/mgmt/brute_force_configuration.json
src/test/resources/mgmt/suspicious_ip_throttling_configuration.json

Adds support for the Attack Protection endpoints, as documented here: https://auth0.com/docs/api/management/v2#!/Attack_Protection/get_breached_password_detection

[SDK-3116] Add support for Attack Protection APIs

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/auth/AuthorizeUrlBuilder.java
src/main/java/com/auth0/client/auth/LogoutUrlBuilder.java

As discussed in #390, the documentation for generating the authorize (and logout) URLs is wrong. The docs state that the URLs should be encoded, though the validation will fail when it is encoded.
We may make a change to encode the redirect/returnTo URLs, but that may need to go into the next major release to avoid any unintended consequences of changing the current behavior.

[SDK-3098] Fix documentation for authorize and logout URL creation

---

build.gradle

This PR bumps the `jackson-databind` dependency to 2.13.2. This addresses [CVE-2020-36518](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518) for that dependency.
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518

Bump `jackson-databind` dependency to 2.13.2

---

build.gradle

This PR bumps the `jackson-databind` dependency to 2.13.2.1 to address [CVE-2020-36518](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518) in that library
---
~~Re: https://togithub.com/FasterXML/jackson-databind/issues/3428
Build is currently failing due to an upstream issue; holding until resolved.~~
---
A package fix was released as 2.13.2.2. I've updated the PR and marked as ready for review.

Security: Bump `jackson-databind` to 2.13.2.2

---

build.gradle

This PR bumps the `java-jwt` dependency to 3.19.1 to address [CVE-2020-36518](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518) due to transitive dependency in `jackson-databind`

Bump java-jwt to 3.19.1

---

CHANGELOG.md
README.md

[Full Changelog](https://github.com/auth0/auth0-java/compare/1.40.0...1.40.1)
**Security**
- Bump java-jwt to 3.19.1 [\#415](https://github.com/auth0/auth0-java/pull/415) ([poovamraj](https://github.com/poovamraj))
- Security: Bump `jackson-databind` to 2.13.2.2 [\#414](https://github.com/auth0/auth0-java/pull/414) ([evansims](https://github.com/evansims))

Release 1.40.1

---

build.gradle

Update OkHttp dependency to 4.9.3 to address [CVE-2021-0341](https://nvd.nist.gov/vuln/detail/CVE-2021-0341)

Update OkHttp to address CVE-2021-0341

---

CHANGELOG.md
README.md

Release 1.40.2.
**Security**
- Update OkHttp to address CVE-2021-0341 [\#417](https://github.com/auth0/auth0-java/pull/417) ([lbalmaceda](https://github.com/lbalmaceda))

Release 1.40.2

---

src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java

Log event filter query params are being double-encoded as demonstrated in #419. This change doesn't double-encode the filter query, similar to how we do not encode it in `UsersEntity#list`.

Fix double-encoding of log event filter query param

---

src/main/java/com/auth0/exception/APIException.java
src/test/java/com/auth0/exception/APIExceptionTest.java

As raised in #410, there are (rare) occasions when the Auth0 error responses are not strings. We construct an `APIException` from the response when there is a response body ([see here](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/net/ExtendedBaseRequest.java#L127)), passing in a map of `<String, Object>` values parsed from the response.
When constructing the `APIException`, we set the description and error using the values, but casting them to a String ([see here](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/exception/APIException.java#L131)).
This change sets the description and error by calling `toString()` on the object if not null, else sets it to `null`.
Fixes #410.

Do not cast error values to String

---

src/main/java/com/auth0/json/mgmt/organizations/Organization.java
src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
src/test/java/com/auth0/json/mgmt/organizations/OrganizationsTest.java
src/test/resources/mgmt/organization.json

This PR adds the possibility to set Enabled Connections on an Organization on create, which so far could only be done after creating the organization and only one connection at a time. Changes:
- Added enabled_connections property on Organization
- Fixed tests to include enabled_connections
https://github.com/auth0/auth0-java/issues/425
https://auth0.com/changelog#6BBzbWOwkhEZdzauu2s0Bg
This can be tested by adding enabled connections when creating an organization. I have modified some tests to check for enabled_connections. I have not added tests specific to enabled_connections, I have only modified shouldCreateOrganization, shouldSerialize and shouldDeserialize.

Add enabled connections on organization

---

src/main/java/com/auth0/client/auth/AuthAPI.java

Changes to documentation which had unsupported characters. This caused issues while generating Java docs

Removed unsupported characters in documentation

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/utils/Asserts.java
src/test/java/com/auth0/utils/AssertsTest.java

We are adding support for Custom schemes. This is done using existing HttpUrl method but just changing the value before `:` if it is a custom domain. We are not using Java's URI class since it doesn't validate unencoded URLs and we do not want to break the existing behaviour of the SDK
Issue - https://github.com/auth0/auth0-java/issues/424
Previous PR - https://github.com/auth0/auth0-java/pull/428
We have added tests to check the URL and all the existing tests pass without change

Support for custom scheme URL

---

src/main/java/com/auth0/client/mgmt/KeysEntity.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/json/mgmt/Key.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/KeysEntityTest.java
src/test/java/com/auth0/json/mgmt/KeyTest.java
src/test/resources/mgmt/key.json
src/test/resources/mgmt/key_list.json
src/test/resources/mgmt/key_revoke.json
src/test/resources/mgmt/key_rotate.json

We have added support for Management API of Keys. Added the following methods
- List all keys
- Get key
- Revoke key
- Rotate key
[#430](https://github.com/auth0/auth0-java/issues/430)
Did manual testing for all the newly added methods. Added Unit tests as well.

Added support for Key management API

---

.circleci/config.yml
.shiprc
build.gradle

This PR better prepares the project for integration with our automated releasing tooling
- It tracks the version inside build.gradle
- It configures Ship CLI to replace the version in `build.gradle`
- It configures our ship orb to not prefix the version with `v`.
- It bumps the version of our shipping orb, to use the latest changes.

Update ship orb configuration

---

build.gradle

This PR updates OkHttp to 4.10.0 to resolve [CVE-2022-24329](https://www.cve.org/CVERecord?id=CVE-2022-24329)

Security: Update OkHttp to 4.10.0

---

build.gradle

This PR ensures the version property is defined before the plugins are applied, to ensure we can use it in the LibraryPlugin's apply method.
https://github.com/auth0/oss-library-gradle-plugin/pull/32

Ensure version is defined before plugins are applied

---

.circleci/config.yml
settings.gradle

Bump OSS-library to use the latest version to ensure we are set for releasing using the latest version of Auth0/Ship

Bump oss-library and auth0/ship

---

.circleci/config.yml

This PR replaces the deprecated Codecov “bash uploader” for the recommended CircleCI Orb equivalent.

Replace Codecov uploader w/ CircleCI Orb

---

src/main/java/com/auth0/client/mgmt/ClientsEntity.java
src/test/java/com/auth0/client/mgmt/ClientsEntityTest.java

Current auth0-java SDK does not provide filter option to "get Client By Id" API, which is available in auth0-management API
This feature is useful if we intend to read only limited client fields.
Solution here is - Adding new method to ClientsEntity.java, which accepts "FieldsFilter" parameter
- Feature Requested
https://github.com/auth0/auth0-java/issues/448
Locally tested by connecting to real auth0

#448 Adding field filter option to get client by ID API

---

src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java

Adds support for deleting all an user's authenticators.
See the [API docs](https://auth0.com/docs/api/management/v2#!/Users/delete_authenticators) for definition of this API.

Add support for deleting all user's authenticators

---

.circleci/config.yml
build.gradle

Reverts changes made that rely on using the Ship Orb, making it impossible to release manually.
Reverting this until we have fixed the Ship Orb for Java.

Remove Ship Orb integration

---

src/main/java/com/auth0/json/mgmt/attackprotection/BreachedPassword.java
src/main/java/com/auth0/json/mgmt/attackprotection/BreachedPasswordStage.java
src/main/java/com/auth0/json/mgmt/attackprotection/BreachedPasswordStageEntry.java
src/test/java/com/auth0/client/mgmt/AttackProtectionEntityTest.java
src/test/resources/mgmt/breached_password_settings.json

Adds support for the stages property on Breached Password Detection configuration. Similar to Suspicious IP Throttling this is used to configured the shields applied at different stages. Currently only pre-user-registration is supported
See linked tickets on SDK-3640

Support stage property on Breached Password Detection

---

src/main/java/com/auth0/json/mgmt/tenants/SessionCookie.java
src/main/java/com/auth0/json/mgmt/tenants/Tenant.java
src/test/java/com/auth0/json/mgmt/tenants/TenantTest.java
src/test/resources/mgmt/tenant.json

Adds support for the `session_cookie` field on a `Tenant`.
See https://auth0.com/docs/api/management/v2#!/Tenants/tenant_settings_route and https://auth0.com/docs/api/management/v2#!/Tenants/patch_settings

[SDK-2558] Add support for tenant session cookie

---

.circleci/config.yml
.shiprc

Fixes the `.shiprc` build.gradle version replacement expression and update ship-orb (see https://github.com/auth0/ship-orb/pull/17)

Fix ship build.gradle version replacement expression

---

.shiprc

When trying to perform a release with `@a0/ship`, was getting an error regarding invalid JSON. I suspect this is coming from the `files` definition in `.shiprc`. The change in this PR escapes the double quote char. When attempting to run ship with this change, I did not receive a JSON parsing error, just a dirty repo error. That should mean that the JSON is valid now. Once this is merged we can try and perform the release again.

escape strings in version sub pattern

---

build.gradle

Resolves https://www.cve.org/CVERecord?id=CVE-2022-42003

Bump `com.fasterxml.jackson.core:jackson-databind` to 2.13.4.2

---

build.gradle

Updates to v3.19.3 of `java-jwt` which includes fix for Resolves https://www.cve.org/CVERecord?id=CVE-2022-42003.

Bump `java-jwt` to 3.19.3

---

CHANGELOG.md
README.md
build.gradle

**Security**
- Bump `java-jwt` to 3.19.3 [\#465](https://github.com/auth0/auth0-java/pull/465) ([jimmyjames](https://github.com/jimmyjames))
- Bump `com.fasterxml.jackson.core:jackson-databind` to 2.13.4.2 [\#464](https://github.com/auth0/auth0-java/pull/464) ([evansims](https://github.com/evansims))

Release 1.44.1

---

.circleci/config.yml

Disables the API diff checking in v2, as there will be breaking changes in v2.

disable API diff checks for v2

---

build.gradle
settings.gradle
src/test/java/com/auth0/net/TelemetryTest.java

- Migrated to OSS plugin with LTS testing support
- Enabled testing for Java 17 and Java 8 (Java 11 is ignored since tests run in this version by default)
- Updated Mockito so that it doesn't fail
⚠️ Looks like Java 17 has changed the Base 64 encoding method, so the tests fail. Need to explore further
Tested plugin working locally

[SDK-3740] Enable LTS testing

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/auth/AuthorizeUrlBuilder.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/auth/AuthorizeUrlBuilderTest.java

Adds support for Authorization Code Flow with PKCE.
* Adds a new method to the `AuthorizeUrlBuilder` to add a `code_challenge` parameter when making the `/authorize` request
* Adds a new method to `AuthAPI` to include the `code_verifier` on the request to `/oauth/token` to exchange the code for the tokens
The implementation of the `code_verifier` and `code_challenge` is left to the user - when we make use of this in `mvc-commons` that library will generate the verifier and its challenge.

[SDK-3742] support Authorization Code + PKCE

---

src/main/java/com/auth0/json/ObjectMapperProvider.java
src/main/java/com/auth0/json/mgmt/PageDeserializer.java
src/main/java/com/auth0/net/CustomRequest.java
src/main/java/com/auth0/net/MultipartRequest.java
src/main/java/com/auth0/net/Telemetry.java
src/test/java/com/auth0/json/ObjectMapperProviderTest.java

`ObjectMapper` is thread-safe and should be reused. This PR adds a new class `ObjectMapperProvider`, which returns a singleton instance for internal usages to process JSON data.

[SDK-3753] Use single ObjectMapper

---

EXAMPLES.md
README.md
src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/net/client/DefaultHttpClient.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/mgmt/BaseMgmtEntityTest.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java

Adds builders for constructing API clients. This affords greater flexibility if/when additional configuration options are added, without having to continually overload constructors.
A follow-up PR will deprecate the existing constructors in favor of the builders.

[SDK-3777] Use builders to construct API client instances

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java

With #474, logging and telemetry configuration are done on the Http client, not the API clients themselves. This change removes methods from the API clients related to logging and telemetry configuration.

[SDK-3837] Remove obsolete methods from API clients

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java

Deprecates the API client constructors in favor of the builders introduced in #475

[SDK-3836] deprecate API client constructors

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/test/java/com/auth0/client/auth/AuthAPITest.java

This change enables the `AuthAPI` to be created without a client secret. The reasons for doing so are:
* Some APIs, such as signup or user info, never require a client secret
* Requiring a client secret makes it difficult to use the API client in native applications (an empty string could be used previously to satisfy the null-checks, but is not usable and still results in the client_secret param being sent in cases where it is not desired)
* Certain flows such as implicit with form_post for webapp login do not require a secret
The following operations always require a client secret, and attempting to call them with a client instantiated without one will result in an `InvalidStateException`:
* `public TokenRequest login(String emailOrUsername, char[] password)` - [Resource Owner Password …

[SDK-3745] Update AuthAPI to not require client secret

---

src/main/java/com/auth0/client/HttpOptions.java
src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ClientGrantsEntity.java
src/main/java/com/auth0/client/mgmt/ClientsEntity.java
src/main/java/com/auth0/client/mgmt/ConnectionsEntity.java
src/main/java/com/auth0/client/mgmt/GrantsEntity.java
src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/client/mgmt/ResourceServerEntity.java
src/main/java/com/auth0/client/mgmt/RulesEntity.java
src/main/java/com/auth0/json/mgmt/guardian/EnrollmentTicket.java
src/main/java/com/auth0/json/mgmt/guardian/SNSFactorProvider.java
src/main/java/com/auth0/json/mgmt/guardian/TwilioFactorProvider.java
src/main/java/com/auth0/net/RateLimitInterceptor.java
src/test/java/com/auth0/client/HttpOptionsTest.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/mgmt/ClientGrantsEntityTest.java
src/test/java/com/auth0/client/mgmt/ClientsEntityTest.java
src/test/java/com/auth0/client/mgmt/ConnectionsEntityTest.java
src/test/java/com/auth0/client/mgmt/GrantsEntityTest.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java
src/test/java/com/auth0/client/mgmt/ResourceServerEntityTest.java
src/test/java/com/auth0/client/mgmt/RulesEntityTest.java
src/test/java/com/auth0/json/mgmt/guardian/SNSFactorProviderTest.java
src/test/java/com/auth0/json/mgmt/guardian/TwilioFactorProviderTest.java

This PR removes existing deprecated methods, and deprecates `HttpOptions` in favor of `DefaultHttpClient` configuration.

Remove deprecated methods

---

CHANGELOG.md
README.md

[Full Changelog](https://github.com/auth0/auth0-java/compare/1.44.1...1.44.2)
This patch release does not contain any functional changes, but is being released using an updated signing key for verification as part of our commitment to best security practices.
Please review [the README note for additional details.](https://github.com/auth0/auth0-java/blob/master/README.md)
**Security**
- Bump java-jwt dependency to 3.19.4 [\#498](https://github.com/auth0/auth0-java/pull/498) ([jimmyjames](https://github.com/jimmyjames))

Release 1.44.2

---

CHANGELOG.md
README.md

[Full Changelog](https://github.com/auth0/auth0-java/compare/1.44.2...2.0.0-beta.0)
> **Warning** This SDK is in beta and is subject to breaking changes. It is not recommended for production use, but your feedback and help in testing is appreciated!
This release introduces several enhancement, including:
- HTTP response information returned from requests
- Additional HTTP client configurability
- Authentication API improvements to not require a client secret
- ... and more!
Please see the Migration Guide for guidance on updating your application.

Release 2.0.0-beta.0

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/json/auth/CreatedOTPResponse.java
src/main/java/com/auth0/json/auth/CreatedOobResponse.java
src/main/java/com/auth0/json/auth/CreatedOtpResponse.java
src/main/java/com/auth0/json/auth/MfaAuthenticator.java
src/main/java/com/auth0/json/auth/MfaChallengeResponse.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/resources/auth/add_oob_authenticator_response.json
src/test/resources/auth/add_otp_authenticator_response.json
src/test/resources/auth/list_authenticators_response.json
src/test/resources/auth/mfa_challenge_request_response.json

This change adds support for the following MFA APIs to the AuthAPI client:
- [Challenge request](https://auth0.com/docs/api/authentication#challenge-request)
- [Verify with OTP](https://auth0.com/docs/api/authentication#verify-with-one-time-password-otp-)
- [Verify with OOB](https://auth0.com/docs/api/authentication#verify-with-out-of-band-oob-)
- [Verify with recovery code](https://auth0.com/docs/api/authentication#verify-with-recovery-code)
- [Add an authenticator](https://auth0.com/docs/api/authentication#add-an-authenticator)
- [List authenticators](https://auth0.com/docs/api/authentication#list-authenticators)
Note that this PR does not include the DELETE endpoint, as it [appears to not be working as documented](https://community.auth0.com/t/when-deleting-authenticator-it-says-mfa-tok …

[SDK-3746] Add support for MFA APIs

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/test/java/com/auth0/client/auth/AuthAPITest.java

Adds the ability to make a request to the reset password API specifying a client ID that may be different from the client's configured client ID.
Fixes #510.

Enable ability to specify client ID on reset password request

---

src/main/java/com/auth0/json/mgmt/logevents/LogEvent.java
src/test/java/com/auth0/json/mgmt/logevents/LogEventTest.java

Fixes #519 
Adds support for the following fields to `LogEvent`:
- `hostname`
- `audience`
- `connection`
- `connection_id`
- `description`

Add missing LogEvent fields

---

src/main/java/com/auth0/json/mgmt/users/authenticationmethods/AuthMethod.java
src/main/java/com/auth0/json/mgmt/users/authenticationmethods/AuthenticationMethod.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java
src/test/java/com/auth0/json/mgmt/users/authenticationmethods/AuthenticationMethodTest.java
src/test/resources/mgmt/authenticator_method_list.json
src/test/resources/mgmt/authenticator_method_paged_list.json

The get authentication methods endpoint returns an `authentication_methods` field, which is an array of objects. Prior to this PR, it was defined as an array of strings.
ESD-27129
Updated the existing test json to reflect actual data shape from API call, and added a paged list result JSON as well.

[ESD-27129] authentication_methods is an object, not a string

---

build.gradle

Update Jackson to 2.14.2 ([release notes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14.2))

Bump jackson dependency to 2.14.2

---

CHANGELOG.md
README.md

**Added**
- Add missing LogEvent fields [\#521](https://github.com/auth0/auth0-java/pull/521) ([jimmyjames](https://github.com/jimmyjames)) 
**Changed**
- authentication_methods is an object, not a string [\#520](https://github.com/auth0/auth0-java/pull/520) ([jimmyjames](https://github.com/jimmyjames))
- Bump jackson dependency to 2.14.2 [\#522](https://github.com/auth0/auth0-java/pull/522) ([jimmyjames](https://github.com/jimmyjames))
- Update java-jwt dependency to 4.4.0 [\#523](https://github.com/auth0/auth0-java/pull/523) ([jimmyjames](https://github.com/jimmyjames))

Release 2.1.0

---

src/main/java/com/auth0/client/mgmt/ClientsEntity.java
src/main/java/com/auth0/json/mgmt/client/Client.java
src/main/java/com/auth0/json/mgmt/client/ClientAuthenticationMethods.java
src/main/java/com/auth0/json/mgmt/client/Credential.java
src/main/java/com/auth0/json/mgmt/client/PrivateKeyJwt.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/ClientsEntityTest.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java
src/test/java/com/auth0/json/mgmt/client/CredentialTest.java
src/test/resources/mgmt/client.json
src/test/resources/mgmt/client_credential.json
src/test/resources/mgmt/client_credential_list.json

Adds support for the management of client credentials to the management API client.
https://auth0team.atlassian.net/browse/SDK-3864
In addition to unit tests, verified new methods work with a tenant with the feature enabled.

[SDK-3864] - Add support for client credential management

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/json/auth/PushedAuthorizationResponse.java
src/main/java/com/auth0/json/mgmt/client/Client.java
src/main/java/com/auth0/net/BaseRequest.java
src/main/java/com/auth0/net/FormBodyRequest.java
src/main/java/com/auth0/net/client/Auth0FormRequestBody.java
src/main/java/com/auth0/net/client/DefaultHttpClient.java
src/main/java/com/auth0/net/client/HttpRequestBody.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java
src/test/java/com/auth0/net/FormBodyRequestTest.java
src/test/java/com/auth0/net/client/DefaultHttpClientTest.java
src/test/resources/auth/pushed_authorization_response.json

Adds support for PAR by introducing two new methods on `AuthAPI`:
- `public Request<PushedAuthorizationResponse> pushedAuthorizationRequest(String redirectUri, String responseType, Map<String, String> params)` - Builds a request to make the pushed authorization request.
- `public String authorizeUrlWithPAR(String requestUri)`: Given the `request_uri` obtained from a PAR, constructs the authorize URL.
- https://github.com/auth0/auth0-java/pull/531
- https://www.rfc-editor.org/rfc/rfc6749
In addition to the unit tests, manually tested using a tenant with PAR enabled to verify.

Support Pushed Authorize Requests (PAR)

---

src/main/java/com/auth0/client/mgmt/JobsEntity.java
src/test/java/com/auth0/client/mgmt/JobsEntityTest.java

As discussed in #530, the export users job does not require a `connection_id`, but the `JobsEntity` currently does require it. Further, if the filter contains a `connectionId`, it will override the (required) `connection_id` parameter.
This PR:
* Deprecates the current export users method
* Adds a new export users method that accepts an (optional) filter param
* Adds tests demonstrating the behavior of the now-deprecated method, and tests for the new method
#530

Export users does not require connection_id

---

src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java

Adds support for the [invalidate browsers endpoint](https://auth0.com/docs/api/management/v2#!/Users/post_invalidate_remember_browser).
Fixes #540

Support invalidate remembered browsers endpoint

---

CHANGELOG.md
README.md

**Added**
- Support delete authenticator endpoint [\#541](https://github.com/auth0/auth0-java/pull/541) ([vasantteja](https://github.com/vasantteja))
- Support invalidate remembered browsers endpoint [\#543](https://github.com/auth0/auth0-java/pull/543) ([jimmyjames](https://github.com/jimmyjames))
**Fixed**
- Export users does not require connection_id [\#537](https://github.com/auth0/auth0-java/pull/537) ([jimmyjames](https://github.com/jimmyjames))

Release 2.4.0

---

.github/workflows/gradle-wrapper-validation.yml

This PR pins the `gradle/wrapper-validation-action` third-party action to a full-length commit SHA — that of release 1.0.6.
Pinning an action to a full-length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository. https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
This PR also updates the official `actions/checkout` action to use the newer v3 release.

chore(security): Update and pin Graddle workflow action

---

src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java

`UsersEntity#deleteAuthentiationMethodById()` fails when parsing the response body, since the response is a no-content 204 ([API docs](https://auth0.com/docs/api/management/v2#!/Users/delete_authentication_methods_by_authentication_method_id)). This happens because the implementation was incorrectly using a `BaseRequest` instead of a `VoidRequest`. This PR fixes this by using `VoidRequest` and updates the test. Tested with unit tests and manually.

Fix deleteAuthenticationMethodById

---

src/main/java/com/auth0/client/auth/AuthorizeUrlBuilder.java
src/main/java/com/auth0/utils/tokens/IdTokenVerifier.java
src/test/java/com/auth0/utils/tokens/IdTokenVerifierTest.java

Adds support for using the `org_name` authorize parameter, as well as support for verifying the `org_name` claim.

[SDK-4400] Support Organization Name on Authorize URL

---

src/main/java/com/auth0/json/mgmt/client/Client.java
src/test/resources/mgmt/clients_list.json

- fixes https://github.com/auth0/auth0-java/issues/554
- align attribute with the response documentation https://auth0.com/docs/api/management/v2/clients/get-clients
- go implementation https://github.com/auth0/go-auth0/blob/main/management/client.go#L68C2-L68C2
- Management API docs https://auth0.com/docs/api/management/v2/clients/get-clients
This just change from which attribute of the json the value is extracted

Align json property 'cross_origin_authentication' with api docs

---

.github/workflows/build-and-test.yml
build.gradle

Updates to use GitHub Actions for build and test, replacing CircleCI (change to remove CircleCI will follow)

[SDK-4388] Use GitHub Actions

---

CHANGELOG.md
build.gradle

This pull request updates the OkHttp dependency to address a moderate security vulnerability in the imported version. This bumps the included release to 4.11.0 to address [CVE-2023-3635](https://www.cve.org/CVERecord?id=CVE-2023-3635).
Please see internal ticket SDK-4501.
No added tests were necessary.

build(dependencies): Update OkHttp to 4.11.0 [SDK-4501]

---

CHANGELOG.md
README.md

**Security**
- Update OkHttp to 4.11.0 [\#558](https://github.com/auth0/auth0-java/pull/558) ([evansims](https://github.com/evansims))
**Fixed**
- Align json property 'cross_origin_authentication' with api docs [\#555](https://github.com/auth0/auth0-java/pull/555) ([Jojo134](https://github.com/Jojo134))

Release 2.6.0

---

build.gradle

Excludes transient dependency okio from OkHttp and include 3.5.0 which resolves CVE-2023-3635. Once OkHttp 4.12.0 is released we can remove the manual okio dependency and exclude rule.

Update Okio to resolve CVE-2023-3635

---

build.gradle

Excludes transient dependency okio from OkHttp and include 3.5.0 which resolves CVE-2023-3635. Once OkHttp 4.12.0 is released we can remove the manual okio dependency and exclude rule.

(v1) Update Okio to resolve CVE-2023-3635

---

CHANGELOG.md
README.md

Release 2.6.1
**Security**
- Update Okio to resolve CVE-2023-3635 [\#560](https://github.com/auth0/auth0-java/pull/560) ([evansims](https://github.com/evansims))

Release 2.6.1

---

CHANGELOG.md
README.md

Release 1.45.1
**Security**
- Update Okio to resolve CVE-2023-3635 [\#562](https://github.com/auth0/auth0-java/pull/562) ([jimmyjames](https://github.com/jimmyjames))

Release 1.45.1

---

src/main/java/com/auth0/client/mgmt/OrganizationsEntity.java
src/main/java/com/auth0/json/mgmt/organizations/Member.java
src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
src/test/java/com/auth0/json/mgmt/organizations/MembersTest.java

This change adds support for sending the `fields` and `include_fields` parameters to the `GET /api/v2/organizations/{orgId/members` endpoint.
```java
// return fields roles, email, name, user_id
FieldsFilter fieldsFilter = new FieldsFilter().withFields("roles,email,name,user_id", true);
List<Member> membersList = managementAPI.organizations().getMembers("orgId", pageFilter, fieldsFilter)
.execute()
.getBody()
.getItems();
Role firstMemberRole = membersList.get(0).getRoles();
```
Fixes #573

[SDK-4654] support organization get member roles

---

src/main/java/com/auth0/json/mgmt/users/authenticationmethods/AuthenticationMethod.java
src/test/java/com/auth0/json/mgmt/users/authenticationmethods/AuthenticationMethodTest.java
src/test/resources/mgmt/authenticator_method_list.json

Adds the passkey properties to the AuthenticationMethod model.

[SDK-4556] Add passkey properties to authentication method response

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/exception/RateLimitException.java
src/main/java/com/auth0/net/BaseRequest.java
src/main/java/com/auth0/net/RateLimitInterceptor.java
src/main/java/com/auth0/net/client/DefaultHttpClient.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/net/BaseRequestTest.java
src/test/java/com/auth0/net/MultipartRequestTest.java
src/test/java/com/auth0/net/RateLimitInterceptorTest.java
src/test/java/com/auth0/net/client/DefaultHttpClientTest.java
src/test/resources/mgmt/rate_limit_error.json

Prior to this change, any error messages returned from Auth0 APIs caused by a 429 (rate limit exceeded) were not propagated to the exception. This change updates the `RateLimitException` class to accept message parameters, populates those values from the response, and updates the `RateLimitInterceptor` to not eagerly close responses on retry, which was causing the inability to retrieve the response body (it was already closed).

propagate error message on rate limit exception

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/client/mgmt/ClientGrantsEntity.java
src/main/java/com/auth0/client/mgmt/OrganizationsEntity.java
src/main/java/com/auth0/client/mgmt/filter/OrganizationClientGrantsFilter.java
src/main/java/com/auth0/json/mgmt/organizations/CreateOrganizationClientGrantRequestBody.java
src/main/java/com/auth0/json/mgmt/organizations/OrganizationClientGrant.java
src/main/java/com/auth0/json/mgmt/organizations/OrganizationClientGrantsPage.java
src/main/java/com/auth0/json/mgmt/organizations/OrganizationClientGrantsPageDeserializer.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/java/com/auth0/client/mgmt/ClientGrantsEntityTest.java
src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
src/test/java/com/auth0/json/mgmt/ClientGrantTest.java
src/test/java/com/auth0/json/mgmt/organizations/OrganizationClientGrantTest.java
src/test/java/com/auth0/json/mgmt/organizations/OrganizationClientGrantsPageTest.java
src/test/resources/mgmt/organization_client_grant.json
src/test/resources/mgmt/organization_client_grants.json
src/test/resources/mgmt/organization_client_grants_paged_list.json

- New method to create a `client_credentials` request to `/oauth/token` allowing the optional `organization` parameter
- Updated `ClientsGrantEntity` to support getting, creating, and updating client grants with respect to organizations
- Updated `OrganizationsEntity` to support getting, associating, and removing client grants associated with an organization

[SDK-4542] Support organization in client credentials

---

src/main/java/com/auth0/json/mgmt/client/Client.java
src/main/java/com/auth0/json/mgmt/client/OIDCBackchannelLogout.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java

Adds support for the `oidc_backchannel_logout` property on a `Client`.

[SDK-4736] support backchannel logout property on Client

---

.snyk
src/main/java/com/auth0/json/mgmt/organizations/Organization.java
src/test/java/com/auth0/json/mgmt/organizations/OrganizationsTest.java

The Organizations API no longer returns the `enabled_connections` property.
* [https://auth0.com/docs/api/management/v2/organizations/get-organizations-by-id](https://auth0.com/docs/api/management/v2/organizations/get-organizations-by-id)
* [https://auth0.com/docs/api/management/v2/organizations/get-organizations-by-id](https://auth0.com/docs/api/management/v2/organizations/get-name-by-name)
This PR deprecates `getEnabledConnections()` in favor of `OrganizationsEntity#getConnections`.

Organizations API no longer returns enabled_connections

---

.snyk

Adds snyk rule to ignore test-only dependency of bouncy castle:
- https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6277380
- https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6613080

Ignore test-only dependency snyk issue

---

src/main/java/com/auth0/json/mgmt/organizations/EnabledConnection.java
src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
src/test/resources/mgmt/organization_connection.json
src/test/resources/mgmt/organization_connections_list.json
src/test/resources/mgmt/organization_connections_paged_list.json

Adds the `show_as_button` field to organization enabled connections.
https://auth0.com/docs/api/management/v2/organizations/get-enabled-connections
https://auth0.com/docs/api/management/v2/organizations/post-enabled-connections
https://auth0.com/docs/api/management/v2/organizations/get-enabled-connections-by-connection-id
https://auth0.com/docs/api/management/v2/organizations/patch-enabled-connections-by-connection-id

[SDK-4769] - add show_as_button to Organization Enabled Connections

---

src/main/java/com/auth0/json/mgmt/client/Client.java
src/main/java/com/auth0/json/mgmt/client/ClientAuthenticationMethods.java
src/main/java/com/auth0/json/mgmt/client/Credential.java
src/main/java/com/auth0/json/mgmt/client/SelfSignedTLSClientAuth.java
src/main/java/com/auth0/json/mgmt/client/SignedRequest.java
src/main/java/com/auth0/json/mgmt/client/TLSClientAuth.java
src/main/java/com/auth0/json/mgmt/resourceserver/AuthorizationDetails.java
src/main/java/com/auth0/json/mgmt/resourceserver/EncryptionKey.java
src/main/java/com/auth0/json/mgmt/resourceserver/ResourceServer.java
src/main/java/com/auth0/json/mgmt/resourceserver/TokenEncryption.java
src/main/java/com/auth0/json/mgmt/tenants/Mtls.java
src/main/java/com/auth0/json/mgmt/tenants/Tenant.java
src/test/java/com/auth0/json/JsonMatcher.java
src/test/java/com/auth0/json/mgmt/ResourceServerTest.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java
src/test/java/com/auth0/json/mgmt/tenants/TenantTest.java
src/test/resources/mgmt/client.json
src/test/resources/mgmt/resource_server.json
src/test/resources/mgmt/tenant.json

Adds support for new and modified management endpoints related to [Highly Regulated Identity](https://auth0.com/docs/secure/highly-regulated-identity) (HRI).
Endpoints changed:
- new field `acr_values_supported` on Tenant
- new field `pushed_authorization_requests_supported` on Tenant
- new field `remove_alg_from_jwks` on Tenant
- new field `mtls` on Tenant
- new field `require_pushed_authorization_requests` on Client
- new field `signed_request_object` on Client
- new field `compliance_level` on Client
- new field `tls_client_auth` on `client_authentication_methods` field of Client
- new field `self_signed_tls_client_auth` on `client_authentication_methods` field of Client
- new field `require_proof_of_possession` on Client
- new field `consent_policy` on Resource Server
- new field …

[SDK-4763] - Add support for HRI Management API changes 

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/test/java/com/auth0/client/auth/AuthAPITest.java

Adds support for Rich Authorization Requests (RAR) to the `/par` endpoint. 
Two new public methods have been added to `AuthAPI`. Both methods accept a list of maps, which will be serialized to url-form-encoded json.
- `public Request<PushedAuthorizationResponse> pushedAuthorizationRequest(String redirectUri, String responseType, Map<String, String> params, List<Map<String, Object>> authorizationDetails)`
- `public Request<PushedAuthorizationResponse> pushedAuthorizationRequestWithJAR(String request, List<Map<String, Object>> authorizationDetails)`
- [Authorization Code Exchange with Rich Authorization Requests (RAR)](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow/authorization-code-flow-with-rar)
- [OAuth 2.0 Rich Authorization …

[SDK-4763] - RIch Authorization Request (RAR)

---

src/main/java/com/auth0/client/mgmt/UsersEntity.java
src/test/java/com/auth0/client/mgmt/UsersEntityTest.java

Adds new method `deleteAllAuthenticationMethods(String userId)` to the `UsersEntity` to delete all authenticators for the given user.
Calls the [delete all authenticators endpoint](https://auth0.com/docs/api/management/v2/users/delete-authentication-methods)

Support delete all authentication methods endpoint

---

.github/actions/maven-publish/action.yml
.github/workflows/java-release.yml
build.gradle
gradle.properties
gradle/maven-publish.gradle
gradle/versioning.gradle
settings.gradle

Changes
Modified Github workflow and gradle plugins
References
https://github.com/auth0/Auth0.Android/pull/739

Fix maven release changes

---

src/main/java/com/auth0/json/mgmt/client/Client.java
src/main/java/com/auth0/json/mgmt/resourceserver/ProofOfPossession.java
src/main/java/com/auth0/json/mgmt/resourceserver/ResourceServer.java
src/test/java/com/auth0/json/mgmt/ResourceServerTest.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java
src/test/resources/mgmt/client.json
src/test/resources/mgmt/resource_server.json

Changes
Adds support for new and modified management endpoints related to [Highly Regulated Identity](https://auth0.com/docs/secure/highly-regulated-identity) (HRI).
Endpoints changed:
new field proof_of_possession on Resource Server
new field require_proof_of_possession on Client

Added support for HRI phase 2 changes

---

src/main/java/com/auth0/client/mgmt/filter/ClientFilter.java
src/main/java/com/auth0/client/mgmt/filter/OrganizationClientGrantsFilter.java
src/main/java/com/auth0/client/mgmt/filter/ResourceServersFilter.java
src/main/java/com/auth0/json/mgmt/client/Client.java
src/main/java/com/auth0/json/mgmt/client/ClientDefaultOrganization.java
src/test/java/com/auth0/client/mgmt/ClientsEntityTest.java
src/test/java/com/auth0/client/mgmt/OrganizationEntityTest.java
src/test/java/com/auth0/client/mgmt/ResourceServerEntityTest.java
src/test/java/com/auth0/json/mgmt/client/ClientTest.java

- Added default_organization field in Client
- Added query parameter "q" in ClientFilter
- Added query parameter "identifiers", "from" and "take" in ResourceServersFilter
- Added query parameter "grants_ids" in OrganizationClientGrantsFilter
- https://github.com/auth0/go-auth0/pull/432/files

Added client credentials changes

---

src/main/java/com/auth0/client/mgmt/KeysEntity.java
src/main/java/com/auth0/net/EmptyBodyVoidRequest.java
src/test/java/com/auth0/client/mgmt/KeysEntityTest.java
src/test/java/com/auth0/net/EmptyBodyVoidRequestTest.java

- added rekey endpoint in KeyEntity
- created custom request class called EmptyBodyVoidRequest
https://github.com/auth0/node-auth0/pull/1041

SDKs support for Control Your Own Key

---

src/main/java/com/auth0/client/mgmt/KeysEntity.java
src/main/java/com/auth0/client/mgmt/filter/EncryptionKeyFilter.java
src/main/java/com/auth0/json/mgmt/keys/EncryptionKey.java
src/main/java/com/auth0/json/mgmt/keys/EncryptionKeysPage.java
src/main/java/com/auth0/json/mgmt/keys/EncryptionKeysPageDeserializer.java
src/main/java/com/auth0/json/mgmt/keys/EncryptionWrappingKeyResponse.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/KeysEntityTest.java
src/test/java/com/auth0/json/mgmt/keys/EncryptionKeyTest.java
src/test/java/com/auth0/json/mgmt/keys/EncryptionKeysPageTest.java
src/test/java/com/auth0/json/mgmt/keys/EncryptionWrappingKeyResponseTest.java
src/test/java/com/auth0/json/mgmt/keys/KeyTest.java
src/test/resources/mgmt/encryption_key.json
src/test/resources/mgmt/encryption_keys_list.json

- Added Endpoints 
1. GET `api/v2/keys/encryption`
2. GET `api/v2/keys/encryption/{kid}`
3. POST `api/v2/keys/encryption`
4. POST `api/v2/keys/encryption/{kid}`
5. DELETE `api/v2/keys/encryption/{kid}`
6. POST `api/v2/keys/encryption/{kid}/wrapping-key`

Added support for byok

---

src/main/java/com/auth0/client/auth/AuthAPI.java
src/main/java/com/auth0/json/auth/CreatedUser.java
src/test/java/com/auth0/client/auth/AuthAPITest.java
src/test/resources/auth/sign_up_username.json

added a new method, that takes phone number as identifier
https://auth0.com/docs/api/authentication#signup

Added phone number identifier in signup Auth API

---

src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/client/mgmt/PromptsEntity.java
src/main/java/com/auth0/json/mgmt/prompts/Prompt.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/PromptsEntityTest.java
src/test/resources/mgmt/custom_text_prompt.json
src/test/resources/mgmt/partials_prompt.json
src/test/resources/mgmt/prompt.json

- Created new PromptEntity class and added new methods getPrompt, updatePrompt, getCustomText, setCustomText, getPartialsPrompt, setPartialsPrompt 
- Created new Prompts class
[Auth API - Get Prompt Settings](https://auth0.com/docs/api/management/v2/prompts/get-prompts)
[Auth API - Update Prompt Settings](https://auth0.com/docs/api/management/v2/prompts/patch-prompts)
[Auth API - Get Custom Text](https://auth0.com/docs/api/management/v2/prompts/get-custom-text-by-language)
[Auth API - Set Custom Text](https://auth0.com/docs/api/management/v2/prompts/put-custom-text-by-language)
[Auth API - Get Partials](https://auth0.com/docs/api/management/v2/prompts/get-partials)
[Auth API - Set Partials](https://auth0.com/docs/api/management/v2/prompts/put-partials)
Please describe how this can be …

Added support for custom prompts

---

src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/main/java/com/auth0/client/mgmt/SelfServiceProfilesEntity.java
src/main/java/com/auth0/client/mgmt/filter/PageBasedPaginationFilter.java
src/main/java/com/auth0/json/mgmt/selfserviceprofiles/Branding.java
src/main/java/com/auth0/json/mgmt/selfserviceprofiles/Color.java
src/main/java/com/auth0/json/mgmt/selfserviceprofiles/SelfServiceProfile.java
src/main/java/com/auth0/json/mgmt/selfserviceprofiles/SelfServiceProfileResponse.java
src/main/java/com/auth0/json/mgmt/selfserviceprofiles/SelfServiceProfileResponsePage.java
src/main/java/com/auth0/json/mgmt/selfserviceprofiles/SelfServiceProfileResponsePageDeserializer.java
src/main/java/com/auth0/json/mgmt/selfserviceprofiles/SsoAccessTicketResponse.java
src/main/java/com/auth0/json/mgmt/selfserviceprofiles/UserAttribute.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/SelfServiceProfilesEntityTest.java
src/test/java/com/auth0/client/mgmt/filter/PageBasedPaginationFilterTest.java
src/test/java/com/auth0/json/mgmt/selfserviceprofiles/SelfServiceProfileResponsePageTest.java
src/test/java/com/auth0/json/mgmt/selfserviceprofiles/SelfServiceProfileResponseTest.java
src/test/java/com/auth0/json/mgmt/selfserviceprofiles/SelfServiceProfileTest.java
src/test/java/com/auth0/json/mgmt/selfserviceprofiles/SsoAccessTicketResponseTest.java
src/test/resources/mgmt/self_service_profile.json
src/test/resources/mgmt/self_service_profile_custom_text.json
src/test/resources/mgmt/self_service_profile_response.json
src/test/resources/mgmt/self_service_profile_sso_ticket.json
src/test/resources/mgmt/self_service_profiles_list.json

- Endpoints added /get-self-service-profiles, /post-self-service-profiles, /get-self-service-profiles-by-id, /delete-self-service-profiles-by-id and /patch-self-service-profiles-by-id, /get-self-service-profile-custom-text, /put-self-service-profile-custom-text, /post-sso-ticket and /post-revoke
- Classes added : 
> SelfServiceProfilesEntity
> PageBasedPaginationFilter
> Branding
> Color
> SelfServiceProfile
> SelfServiceProfileResponse
> SelfServiceProfileResponsePage
> SelfServiceProfileResponsePageDeserializer
> UserAttribute
> SsoAccessTicketResponse
> SelfServiceProfilesEntityTest
[Auth0 Management API v2](https://auth0.com/docs/api/management/v2/self-service-profiles/get-self-service-profiles) 
[Auth0 Management API v2](https://auth0.com/docs/api/management/v2/self-service-profiles/p …

Added Support for Self-Service-Profile

---

build.gradle
src/test/java/com/auth0/utils/tokens/SignatureVerifierTest.java

Removing bounycastle test implemntations
- support ticket
- community post
- StackOverflow post
- support forum thread

Remove bounycastle test implementations

---

src/main/java/com/auth0/client/mgmt/ConnectionsEntity.java
src/main/java/com/auth0/json/mgmt/connections/DefaultScimMappingResponse.java
src/main/java/com/auth0/json/mgmt/connections/Mapping.java
src/main/java/com/auth0/json/mgmt/connections/ScimConfigurationRequest.java
src/main/java/com/auth0/json/mgmt/connections/ScimConfigurationResponse.java
src/main/java/com/auth0/json/mgmt/connections/ScimTokenBaseResponse.java
src/main/java/com/auth0/json/mgmt/connections/ScimTokenCreateResponse.java
src/main/java/com/auth0/json/mgmt/connections/ScimTokenRequest.java
src/main/java/com/auth0/json/mgmt/connections/ScimTokenResponse.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/ConnectionsEntityTest.java
src/test/java/com/auth0/json/mgmt/connections/ConnectionTest.java
src/test/java/com/auth0/json/mgmt/connections/ScimConfigurationRequestTest.java
src/test/java/com/auth0/json/mgmt/connections/ScimConfigurationResponseTest.java
src/test/java/com/auth0/json/mgmt/connections/ScimTokenBaseResponseTest.java
src/test/java/com/auth0/json/mgmt/connections/ScimTokenCreateResponseTest.java
src/test/java/com/auth0/json/mgmt/connections/ScimTokenRequestTest.java
src/test/java/com/auth0/json/mgmt/connections/ScimTokenResponseTest.java
src/test/resources/mgmt/connection_scim_configuration.json
src/test/resources/mgmt/connection_scim_token.json
src/test/resources/mgmt/connection_scim_tokens.json
src/test/resources/mgmt/default_connection_scim_configuration.json

- Added endpoints 
- GET  /api/v2/connections/{id}/scim-configuration
- DELETE  /api/v2/connections/{id}/scim-configuration
- PATCH  /api/v2/connections/{id}/scim-configuration
- POST  /api/v2/connections/{id}/scim-configuration
- GET  /api/v2/connections/{id}/scim-configuration/default-mapping
- GET  /api/v2/connections/{id}/scim-configuration/tokens
- POST  /api/v2/connections/{id}/scim-configuration/tokens
- DELETE  /api/v2/connections/{id}/scim-configuration/tokens/{tokenId}
- GET  /api/v2/connections/{id}/status
- Added class 
- Mapping
- ScimConfigurationRequest
- ScimConfigurationResponse
- ScimTokenBaseResponse
- ScimTokenCreateResponse
- ScimTokenRequest
- ScimTokenResponse
https://auth0.com/docs/api/management/v2/connections/get-scim-configuration …

Added Connection's SCIM Server Support

---

src/main/java/com/auth0/client/mgmt/SessionsEntity.java
src/test/java/com/auth0/client/mgmt/SessionsEntityTest.java

- Added revoke-session endpoint
https://auth0.com/docs/api/management/v2/sessions/revoke-session

Added support for revoke session endpoint

---

build.gradle
src/main/java/com/auth0/client/mgmt/filter/ConnectionFilter.java
src/test/java/com/auth0/client/mgmt/ConnectionsEntityTest.java

Added checkpoint pagination support for /get-connections endpoint
https://auth0.com/docs/api/management/v2/connections/get-connections

Check point pagination support for get connection

---

src/main/java/com/auth0/json/mgmt/logevents/LogEvent.java
src/test/java/com/auth0/json/mgmt/logevents/LogEventTest.java

- Updated the scope field to Object type in LogEvent Class
Using this library, ‘scope’ attribute can be either an array of strings or just a string as suggested from internal team
- Get accessToken, domain from your tenant Get accessToken
```
ManagementAPI api = ManagementAPI.newBuilder(domain, accessToken).build();
LogEventsPage logEventsPage = api.logEvents().list(null).execute().getBody();
List<LogEvent> logEvent = logEventsPage.getItems();
```

Fix log event

---

src/main/java/com/auth0/json/mgmt/connections/Connection.java
src/test/java/com/auth0/client/mgmt/ConnectionsEntityTest.java
src/test/resources/mgmt/connection.json

- Made show_as_button and is_domain_connection optional
[Create Connection](https://auth0.com/docs/api/management/v2/connections/post-connections)
[Update Connection](https://auth0.com/docs/api/management/v2/connections/patch-connections-by-id)
- Get accessToken, domain from your tenant Get accessToken
```
ManagementAPI api = ManagementAPI.newBuilder(domain, accessToken).build();
/* Create Connection */
Connection create = new Connection("Test-Connection", "ad");
create.setDomainConnection(true);
Request<Connection> createCon = api.connections().create(create);
Response<Connection> createConRes = createCon.execute();
Connection createConResp = createConRes.getBody();
/* Update Connection */
Connection update = new Connection();
update.setShowAsButton(true); …
```

Fixed POST/PATCH connection endpoints

---

src/main/java/com/auth0/client/mgmt/ConnectionsEntity.java
src/main/java/com/auth0/client/mgmt/filter/EnabledClientsFilter.java
src/main/java/com/auth0/json/mgmt/connections/Clients.java
src/main/java/com/auth0/json/mgmt/connections/Connection.java
src/main/java/com/auth0/json/mgmt/connections/EnabledClientRequest.java
src/main/java/com/auth0/json/mgmt/connections/EnabledClientResponse.java
src/test/java/com/auth0/client/MockServer.java
src/test/java/com/auth0/client/mgmt/ConnectionsEntityTest.java
src/test/java/com/auth0/json/mgmt/connections/ConnectionTest.java
src/test/java/com/auth0/json/mgmt/connections/EnabledClientRequestTest.java
src/test/java/com/auth0/json/mgmt/connections/EnabledClientResponseTest.java
src/test/resources/mgmt/enabled_clients_for_connection.json

Added 2 New Endpoints
| Path                     | HTTP Method | Method Name |
|--------------------------|-------------|-------------|
| `/connections/{id}/clients`        | GET         | getEnabledClients      |
| `/connections/{id}/clients`        | PATCH        | updateEnabledClients      |
Marked **enabled_clients** field as **Deprecated** in GET/PATCH Connection Endpoints
1. Get domain and apiToken from tenant
```
ManagementAPI mgmt = ManagementAPI.newBuilder("{YOUR_DOMAIN}", "{YOUR_API_TOKEN}").build(); 
EnabledClientResponse enabledClientResponse = api.connections().getEnabledClients("<CONNECTION_ID>", new EnabledClientsFilter().withTake(5)).execute().getBody();
List<Clients> clients = enabledClientResponse.getClients();
List<EnabledClientRequest> requestList = new ArrayList<>(); …
```

Added support for GET/PATCH Connection Endpoints 

---

src/main/java/com/auth0/json/mgmt/refreshtokens/ResourceServer.java
src/test/java/com/auth0/json/mgmt/refreshtokens/RefreshTokenTest.java
src/test/java/com/auth0/json/mgmt/refreshtokens/RefreshTokensPageTest.java
src/test/resources/mgmt/refresh_token.json
src/test/resources/mgmt/user_refresh_tokens.json

Fix: the scopes field for Refresh Token 
https://auth0.com/docs/api/management/v2/users/get-refresh-tokens-for-user
https://auth0.com/docs/api/management/v2/refresh-tokens/get-refresh-token
Get domain and apiToken from tenant
ManagementAPI mgmt = ManagementAPI.newBuilder("{YOUR_DOMAIN}", "{YOUR_API_TOKEN}").build();
```
RefreshTokensPage page = api.users().listRefreshTokens("<USER_ID>", <FILTER>).execute().getBody();
RefreshToken refreshToken = api.refreshTokens().get("<REFRESH_TOKEN_ID>").execute().getBody();
```

Fix: Resource Server Scopes

---

build.gradle
gradle/maven-publish.gradle

Migration of java sdk publishing from OSSRH to Sonatype Central Portal.
Sonatype has announced that the legacy OSSRH service ([oss.sonatype.org](http://oss.sonatype.org/)) will reach end-of-life in June 2025. The auth0 java currently publishes to Maven Central via OSSRH. We need to migrate publishing to the Central Portal ([central.sonatype.com](http://central.sonatype.com/)).

Migrate CI to sonatype central portal

---

src/main/java/com/auth0/client/mgmt/ManagementAPI.java
src/test/java/com/auth0/client/mgmt/ManagementAPITest.java

Support for TokenProvider in Builder:
Added a new static method: newBuilder(String domain, TokenProvider tokenProvider), allowing the creation of a ManagementAPI.Builder using a TokenProvider instead of a raw API token.
Updated the Builder class to accept either an API token (wrapped in a SimpleTokenProvider) or a TokenProvider directly.
The builder now stores a TokenProvider instead of a raw API token.
The build() method now uses the provided TokenProvider directly, instead of always wrapping an API token.
API Token Handling:
The constructor Builder(String domain, String apiToken) now delegates to Builder(String domain, TokenProvider tokenProvider) by wrapping the token in a SimpleTokenProvider.
Thanks @krrrr38 for raising #729.
Please include relevant links supporting this change such …

Customize management api token provider
